#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
error Meh...
#endif

GO(p11_kit_be_loud, vFv)
GO(p11_kit_be_quiet, vFv)
GO(p11_kit_config_option, pFp)
GO(p11_kit_finalize_module, vFp)
GO(p11_kit_finalize_registered, vFv)
GO(p11_kit_initialize_module, LFp)
GO(p11_kit_initialize_registered, vFv)
GO(p11_kit_iter_destroy_object, LFp)
GO(p11_kit_iter_free, vFp)
GO(p11_kit_iter_get_module, pFp)
GO(p11_kit_iter_keep_session, vFp)
GO(p11_kit_iter_load_attributes, LFppL)
GO(p11_kit_iter_next, LFp)
GO(p11_kit_iter_set_uri, vFpp)
GO(p11_kit_load_initialize_module, pFp)
GO(p11_kit_message, pFv)
GO(p11_kit_module_finalize, LFp)
GO(p11_kit_module_for_name, pFp)
GO(p11_kit_module_get_filename, pFp)
GO(p11_kit_module_get_flags, LFp)
GO(p11_kit_module_get_name, pFp)
GO(p11_kit_module_initialize, LFp)
GO(p11_kit_module_load, pFpp)
GO(p11_kit_module_release, vFp)
