#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

GO(xcb_shm_attach, uFbuuC)
GO(xcb_shm_attach_checked, uFbuuC)
GO(xcb_shm_attach_fd, pFbuuC)
GO(xcb_shm_attach_fd_checked, pFbuuC)
GO(xcb_shm_create_pixmap, pFbuuWWCuu)
GO(xcb_shm_create_pixmap_checked, pFbuuWWCuu)
GO(xcb_shm_create_segment, pFbuuC)
GO(xcb_shm_create_segment_reply, pFbup)
GO(xcb_shm_create_segment_reply_fds, pFbp)
GO(xcb_shm_create_segment_unchecked, pFbuuC)
GO(xcb_shm_detach, uFbu)
GO(xcb_shm_detach_checked, uFbu)
GO(xcb_shm_get_image, pFbuwwWWuCuu)
GO(xcb_shm_get_image_reply, pFbup)
GO(xcb_shm_get_image_unchecked, pFbuwwWWuCuu)
DATA(xcb_shm_id, 8)
GO(xcb_shm_put_image, pFbuuWWWWWWwwCCCuu)
GO(xcb_shm_put_image_checked, pFbuuWWWWWWwwCCCuu)
GO(xcb_shm_query_version, uFb)
GO(xcb_shm_query_version_reply, pFbup)
GO(xcb_shm_query_version_unchecked, uFb)
GO(xcb_shm_seg_end, pFpii)
GO(xcb_shm_seg_next, vFp)
