#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

// GO(TIFFGetFieldDefaulted
// GO(TIFFSetField
// GO(TIFFReadEncodedStrip
// GO(TIFFTileSize
// GO(TIFFWarningExt
// GO(TIFFGetTagListCount
// GO(TIFFWriteCheck
// GO(TIFFReadRawTile
// GO(TIFFCurrentStrip
// GO(TIFFFieldTag
// GO(TIFFCurrentDirOffset
// GO(TIFFSetClientInfo
// GO(TIFFJPEGIsFullStripRequired
// GO(TIFFGetSeekProc
// GO(TIFFGetStrileOffset
// GO(TIFFReadTile
// GO(TIFFCurrentRow
// GO(TIFFSwabArrayOfDouble
// GO(TIFFFlushData1
// GO(TIFFGetReadProc
// GO(TIFFInitPackBits
// GO(TIFFComputeStrip
// GO(TIFFInitZIP
// GO(TIFFErrorExt
GO(TIFFSwabLong8, vFp)
GO(TIFFSwabLong, vFp)
// GO(TIFFCreateDirectory
// GO(TIFFPredictorInit
// GO(TIFFPredictorCleanup
// GO(TIFFUnRegisterCODEC
// GO(TIFFFlushData
// GO(TIFFRGBAImageEnd
// GO(TIFFInitSGILog
// GO(TIFFGetTagListEntry
// GO(TIFFWriteEncodedStrip
GO(TIFFClose, vFp)
// GO(TIFFIsBigEndian
// GO(TIFFSwabDouble
// GO(TIFFReadRGBAStripExt
// GO(TIFFLastDirectory
// GO(TIFFInitCCITTRLE
// GO(TIFFSetWriteOffset
// GO(TIFFFieldName
// GO(TIFFFileName
// GO(TIFFScanlineSize
// GO(TIFFDataWidth
// GO(TIFFIsByteSwapped
// GO(TIFFReadBufferSetup
GO(TIFFCIELabToXYZ, vFpuiippp)
// GO(TIFFReadDirectory
// GO(TIFFFieldDataType
// GO(TIFFSetErrorHandlerExt
GO(TIFFIsCODECConfigured, iFW)
// GO(TIFFFaxMainTable
// GO(TIFFReadEXIFDirectory
// GO(TIFFAccessTagMethods
// GO(TIFFGetMapFileProc
// GO(TIFFSetErrorHandler
// GO(TIFFCheckpointDirectory
// GO(TIFFSetClientdata
// GO(TIFFGetVersion
// GO(TIFFWriteRawStrip
// GO(TIFFInitCCITTFax3
// GO(TIFFInitCCITTFax4
// GO(TIFFWriteEncodedTile
// GO(TIFFFieldPassCount
// GO(TIFFReadRGBAImageOriented
// GO(TIFFRGBAImageBegin
// GO(TIFFTileRowSize64
// GO(TIFFRasterScanlineSize
// GO(TIFFSetWarningHandlerExt
// GO(TIFFInitLZW
// GO(TIFFWriteTile
GO(TIFFYCbCrtoRGB, vFpuiippp)
// GO(TIFFSetMode
// GO(TIFFRasterScanlineSize64
// GO(TIFFSwabArrayOfFloat
// GO(TIFFRGBAImageGet
// GO(TIFFVStripSize
// GO(TIFFDefaultTileSize
// GO(TIFFSetFileno
// GO(TIFFGetSizeProc
// GO(TIFFIsUpSampled
// GO(TIFFGetClientInfo
// GO(TIFFDefaultDirectory
// GO(TIFFGetBitRevTable
// GO(TIFFError
// GO(TIFFGetStrileByteCount
// GO(TIFFSetDirectory
// GO(TIFFGetStrileByteCountWithErr
// GO(TIFFFieldWithName
// GO(TIFFRGBAImageOK
GO(TIFFGetConfiguredCODECs, pFW)
// GO(TIFFTileRowSize
// GO(TIFFCreateEXIFDirectory
// GO(TIFFInitJBIG
GO(TIFFXYZToRGB, vFpfffppp)
// GO(TIFFFillTile
// GO(TIFFInitZSTD
// GO(TIFFWriteScanline
// GO(TIFFCreateCustomDirectory
// GO(TIFFVGetFieldDefaulted
// GO(TIFFSetTagExtender
// GO(TIFFStripSize64
// GO(TIFFCurrentDirectory
// GO(TIFFReadRawStrip
// GO(TIFFNumberOfStrips
// GO(TIFFSetupStrips
// GO(TIFFIsMSB2LSB
// GO(TIFFSwabFloat
// GO(TIFFReadRGBAImage
GO(TIFFFreeDirectory, iFp)
GO(TIFFCleanup, vFp)
GO(TIFFFlush, iFp)
GO(TIFFSetCompressionScheme, iFpi)
GO(TIFFSwabShort, vFp)
// GO(TIFFInitNeXT
// GO(TIFFInitDumpMode
// GO(TIFFSwabArrayOfLong8
// GO(TIFFWriteCustomDirectory
// GO(TIFFReverseBits
// GO(TIFFInitWebP
// GO(TIFFCheckTile
// GO(TIFFVGetField
// GO(TIFFTileSize64
// GO(TIFFReadRGBATileExt
// GO(TIFFVTileSize64
// GO(TIFFVSetField
// GO(TIFFDefaultStripSize
// GO(TIFFInitJPEG
// GO(TIFFOpen
// GO(TIFFFaxWhiteCodes
// GO(TIFFUnsetField
// GO(TIFFVTileSize
// GO(TIFFRawStripSize
// GO(TIFFDeferStrileArrayWriting
// GO(TIFFStripSize
GO(TIFFCIELabToRGBInit, iFppp)
// GO(TIFFComputeTile
// GO(TIFFGetField
// GO(TIFFFaxWhiteTable
// GO(TIFFGetUnmapFileProc
// GO(TIFFFillStrip
