#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

//GO(cap_clear, 
//GO(cap_clear_flag, 
//GO(cap_compare, 
//GO(cap_copy_ext, 
//GO(cap_copy_int, 
//GO(cap_drop_bound, 
//GO(cap_dup, 
GO(cap_free, iFp)
//GO(cap_from_name, 
//GO(cap_from_text, 
//GO(cap_get_ambient, 
//GO(cap_get_bound, 
//GO(cap_get_fd, 
//GO(cap_get_file, 
//GO(cap_get_flag, 
//GO(cap_get_mode, 
//GO(cap_get_nsowner, 
//GO(capgetp, 
//GO(cap_get_pid, 
GO(cap_get_proc, pFi)
//GO(cap_get_secbits, 
//GO(cap_iab_fill, 
//GO(cap_iab_from_text, 
//GO(cap_iab_get_proc, 
//GO(cap_iab_get_vector, 
//GO(cap_iab_init, 
//GO(cap_iab_set_proc, 
//GO(cap_iab_set_vector, 
//GO(cap_iab_to_text, 
//GO(cap_init, 
//GO(cap_launch, 
//GO(cap_launcher_callback, 
//GO(cap_launcher_set_chroot, 
//GO(cap_launcher_setgroups, 
//GO(cap_launcher_set_iab, 
//GO(cap_launcher_set_mode, 
//GO(cap_launcher_setuid, 
//GO(cap_max_bits, 
//GO(cap_mode_name, 
//GO(cap_new_launcher, 
//GO(cap_reset_ambient, 
//GO(cap_set_ambient, 
//GO(cap_set_fd, 
//GO(cap_set_file, 
GO(cap_set_flag, iFpiipi)
//GO(cap_setgroups, 
//GO(cap_set_mode, 
//GO(cap_set_nsowner, 
//GO(capsetp, 
GO(cap_set_proc, iFp)
//GO(cap_set_secbits, 
//GO(cap_set_syscall, 
//GO(cap_setuid, 
//GO(cap_size, 
//GO(cap_to_name, 
//GO(cap_to_text, 
//GO(_libcap_strdup, 
//GOW(psx_load_syscalls, 
