#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

//GO(mbedtls_debug_print_buf
//GO(mbedtls_debug_print_crt
//GO(mbedtls_debug_print_ecp
//GO(mbedtls_debug_printf_ecdh
//GO(mbedtls_debug_print_mpi
//GO(mbedtls_debug_print_msg
//GO(mbedtls_debug_print_ret
//GO(mbedtls_debug_set_threshold
//GO(mbedtls_net_accept
//GO(mbedtls_net_bind
//GO(mbedtls_net_close
//GO(mbedtls_net_connect
//GO(mbedtls_net_free
//GO(mbedtls_net_init
//GO(mbedtls_net_poll
//GO(mbedtls_net_recv
//GO(mbedtls_net_recv_timeout
//GO(mbedtls_net_send
//GO(mbedtls_net_set_block
//GO(mbedtls_net_set_nonblock
//GO(mbedtls_net_usleep
//GO(mbedtls_ssl_buffering_free
//GO(mbedtls_ssl_cache_free
//GO(mbedtls_ssl_cache_get
//GO(mbedtls_ssl_cache_init
//GO(mbedtls_ssl_cache_set
//GO(mbedtls_ssl_cache_set_max_entries
//GO(mbedtls_ssl_cache_set_timeout
//GO(mbedtls_ssl_check_cert_usage
//GO(mbedtls_ssl_check_curve
//GO(mbedtls_ssl_check_curve_tls_id
//GO(mbedtls_ssl_check_pending
//GO(mbedtls_ssl_check_record
//GO(mbedtls_ssl_check_sig_hash
//GO(mbedtls_ssl_check_timer
//GO(mbedtls_ssl_ciphersuite_from_id
//GO(mbedtls_ssl_ciphersuite_from_string
//GO(mbedtls_ssl_ciphersuite_uses_ec
//GO(mbedtls_ssl_ciphersuite_uses_psk
//GO(mbedtls_ssl_close_notify
//GO(mbedtls_ssl_conf_alpn_protocols
//GO(mbedtls_ssl_conf_arc4_support
//GO(mbedtls_ssl_conf_authmode
//GO(mbedtls_ssl_conf_ca_chain
//GO(mbedtls_ssl_conf_cbc_record_splitting
//GO(mbedtls_ssl_conf_cert_profile
//GO(mbedtls_ssl_conf_cert_req_ca_list
//GO(mbedtls_ssl_conf_ciphersuites
//GO(mbedtls_ssl_conf_ciphersuites_for_version
//GO(mbedtls_ssl_conf_curves
//GO(mbedtls_ssl_conf_dbg
//GO(mbedtls_ssl_conf_dhm_min_bitlen
//GO(mbedtls_ssl_conf_dh_param
//GO(mbedtls_ssl_conf_dh_param_bin
//GO(mbedtls_ssl_conf_dh_param_ctx
//GO(mbedtls_ssl_conf_dtls_anti_replay
//GO(mbedtls_ssl_conf_dtls_badmac_limit
//GO(mbedtls_ssl_conf_dtls_cookies
//GO(mbedtls_ssl_conf_dtls_srtp_protection_profiles
//GO(mbedtls_ssl_conf_encrypt_then_mac
//GO(mbedtls_ssl_conf_endpoint
//GO(mbedtls_ssl_conf_export_keys_cb
//GO(mbedtls_ssl_conf_export_keys_ext_cb
//GO(mbedtls_ssl_conf_extended_master_secret
//GO(mbedtls_ssl_conf_fallback
//GO(mbedtls_ssl_conf_handshake_timeout
//GO(mbedtls_ssl_config_defaults
//GO(mbedtls_ssl_config_free
//GO(mbedtls_ssl_config_init
//GO(mbedtls_ssl_conf_legacy_renegotiation
//GO(mbedtls_ssl_conf_max_frag_len
//GO(mbedtls_ssl_conf_max_version
//GO(mbedtls_ssl_conf_min_version
//GO(mbedtls_ssl_conf_own_cert
//GO(mbedtls_ssl_conf_psk
//GO(mbedtls_ssl_conf_psk_cb
//GO(mbedtls_ssl_conf_read_timeout
//GO(mbedtls_ssl_conf_renegotiation
//GO(mbedtls_ssl_conf_renegotiation_enforced
//GO(mbedtls_ssl_conf_renegotiation_period
//GO(mbedtls_ssl_conf_rng
//GO(mbedtls_ssl_conf_session_cache
//GO(mbedtls_ssl_conf_session_tickets
//GO(mbedtls_ssl_conf_session_tickets_cb
//GO(mbedtls_ssl_conf_sig_hashes
//GO(mbedtls_ssl_conf_sni
//GO(mbedtls_ssl_conf_srtp_mki_value_supported
//GO(mbedtls_ssl_conf_transport
//GO(mbedtls_ssl_conf_truncated_hmac
//GO(mbedtls_ssl_conf_verify
//GO(mbedtls_ssl_context_load
//GO(mbedtls_ssl_context_save
//GO(mbedtls_ssl_cookie_check
//GO(mbedtls_ssl_cookie_free
//GO(mbedtls_ssl_cookie_init
//GO(mbedtls_ssl_cookie_set_timeout
//GO(mbedtls_ssl_cookie_setup
//GO(mbedtls_ssl_cookie_write
//GO(mbedtls_ssl_decrypt_buf
//GO(mbedtls_ssl_derive_keys
//GO(mbedtls_ssl_dtls_replay_check
//GO(mbedtls_ssl_dtls_replay_reset
//GO(mbedtls_ssl_dtls_replay_update
//GO(mbedtls_ssl_dtls_srtp_set_mki_value
//GO(mbedtls_ssl_encrypt_buf
//GO(mbedtls_ssl_fetch_input
//GO(mbedtls_ssl_flight_free
//GO(mbedtls_ssl_flight_transmit
//GO(mbedtls_ssl_flush_output
//GO(mbedtls_ssl_free
//GO(mbedtls_ssl_get_alpn_protocol
//GO(mbedtls_ssl_get_bytes_avail
//GO(mbedtls_ssl_get_ciphersuite
//GO(mbedtls_ssl_get_ciphersuite_id
//GO(mbedtls_ssl_get_ciphersuite_name
//GO(mbedtls_ssl_get_ciphersuite_sig_alg
//GO(mbedtls_ssl_get_ciphersuite_sig_pk_alg
//GO(mbedtls_ssl_get_current_mtu
//GO(mbedtls_ssl_get_dtls_srtp_negotiation_result
//GO(mbedtls_ssl_get_input_max_frag_len
//GO(mbedtls_ssl_get_key_exchange_md_ssl_tls
//GO(mbedtls_ssl_get_key_exchange_md_tls1_2
//GO(mbedtls_ssl_get_max_frag_len
//GO(mbedtls_ssl_get_max_out_record_payload
//GO(mbedtls_ssl_get_output_max_frag_len
//GO(mbedtls_ssl_get_peer_cert
//GO(mbedtls_ssl_get_record_expansion
//GO(mbedtls_ssl_get_session
//GO(mbedtls_ssl_get_session_pointer
//GO(mbedtls_ssl_get_verify_result
//GO(mbedtls_ssl_get_version
//GO(mbedtls_ssl_handle_message_type
//GO(mbedtls_ssl_handshake
//GO(mbedtls_ssl_handshake_client_step
//GO(mbedtls_ssl_handshake_free
//GO(mbedtls_ssl_handshake_server_step
//GO(mbedtls_ssl_handshake_step
//GO(mbedtls_ssl_handshake_wrapup
//GO(mbedtls_ssl_handshake_wrapup_free_hs_transform
//GO(mbedtls_ssl_hash_from_md_alg
//GO(mbedtls_ssl_init
//GO(mbedtls_ssl_list_ciphersuites
//GO(mbedtls_ssl_md_alg_from_hash
//GO(mbedtls_ssl_optimize_checksum
//GO(mbedtls_ssl_parse_certificate
//GO(mbedtls_ssl_parse_change_cipher_spec
//GO(mbedtls_ssl_parse_finished
//GO(mbedtls_ssl_pk_alg_from_sig
//GO(mbedtls_ssl_prepare_handshake_record
//GO(mbedtls_ssl_psk_derive_premaster
//GO(mbedtls_ssl_read
//GO(mbedtls_ssl_read_record
//GO(mbedtls_ssl_read_version
//GO(mbedtls_ssl_recv_flight_completed
//GO(mbedtls_ssl_renegotiate
//GO(mbedtls_ssl_resend
//GO(mbedtls_ssl_resend_hello_request
//GO(mbedtls_ssl_reset_checksum
//GO(mbedtls_ssl_reset_in_out_pointers
//GO(mbedtls_ssl_send_alert_message
//GO(mbedtls_ssl_send_fatal_handshake_failure
//GO(mbedtls_ssl_send_flight_completed
//GO(mbedtls_ssl_session_copy
//GO(mbedtls_ssl_session_free
//GO(mbedtls_ssl_session_init
//GO(mbedtls_ssl_session_load
//GO(mbedtls_ssl_session_reset
//GO(mbedtls_ssl_session_reset_int
//GO(mbedtls_ssl_session_save
//GO(mbedtls_ssl_set_bio
//GO(mbedtls_ssl_set_calc_verify_md
//GO(mbedtls_ssl_set_client_transport_id
//GO(mbedtls_ssl_set_datagram_packing
//GO(mbedtls_ssl_set_hostname
//GO(mbedtls_ssl_set_hs_authmode
//GO(mbedtls_ssl_set_hs_ca_chain
//GO(mbedtls_ssl_set_hs_own_cert
//GO(mbedtls_ssl_set_hs_psk
//GO(mbedtls_ssl_set_mtu
//GO(mbedtls_ssl_set_session
//GO(mbedtls_ssl_set_timer
//GO(mbedtls_ssl_set_timer_cb
//GO(mbedtls_ssl_setup
//GO(mbedtls_ssl_set_verify
//GO(mbedtls_ssl_sig_from_pk
//GO(mbedtls_ssl_sig_from_pk_alg
//GO(mbedtls_ssl_sig_hash_set_add
//GO(mbedtls_ssl_sig_hash_set_const_hash
//GO(mbedtls_ssl_sig_hash_set_find
//GO(mbedtls_ssl_start_renegotiation
//GO(mbedtls_ssl_ticket_free
//GO(mbedtls_ssl_ticket_init
//GO(mbedtls_ssl_ticket_parse
//GO(mbedtls_ssl_ticket_setup
//GO(mbedtls_ssl_ticket_write
//GO(mbedtls_ssl_tls_prf
//GO(mbedtls_ssl_transform_free
//GO(mbedtls_ssl_transform_init
//GO(mbedtls_ssl_update_handshake_status
//GO(mbedtls_ssl_update_in_pointers
//GO(mbedtls_ssl_update_out_pointers
//GO(mbedtls_ssl_write
//GO(mbedtls_ssl_write_certificate
//GO(mbedtls_ssl_write_change_cipher_spec
//GO(mbedtls_ssl_write_finished
//GO(mbedtls_ssl_write_handshake_msg
//GO(mbedtls_ssl_write_record
//GO(mbedtls_ssl_write_version
