#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

//GO(_INTERNAL_trim_to_complete_utf8_characters, 
//GO(XML_DefaultCurrent, 
GO(XML_ErrorString, pFi)
//GO(XML_ExpatVersion, 
//GO(XML_ExpatVersionInfo, 
//GO(XML_ExternalEntityParserCreate, 
//GO(XML_FreeContentModel, 
//GO(XML_GetBase, 
//GO(XML_GetBuffer, 
//GO(XML_GetCurrentByteCount, 
//GO(XML_GetCurrentByteIndex, 
//GO(XML_GetCurrentColumnNumber, 
GO(XML_GetCurrentLineNumber, iFp)
GO(XML_GetErrorCode, iFp)
//GO(XML_GetFeatureList, 
//GO(XML_GetIdAttributeIndex, 
//GO(XML_GetInputContext, 
//GO(XML_GetParsingStatus, 
//GO(XML_GetSpecifiedAttributeCount, 
//GO(XML_MemFree, 
//GO(XML_MemMalloc, 
//GO(XML_MemRealloc, 
GO(XML_Parse, iFppii)
//GO(XML_ParseBuffer, 
GO(XML_ParserCreate, pFp)
//GO(XML_ParserCreate_MM, 
//GO(XML_ParserCreateNS, 
GO(XML_ParserFree, vFp)
//GO(XML_ParserReset, 
//GO(XML_ResumeParser, 
//GO(XML_SetAttlistDeclHandler, 
//GO(XML_SetBase, 
//GO(XML_SetCdataSectionHandler, 
GOM(XML_SetCharacterDataHandler, vFEpp)
//GO(XML_SetCommentHandler, 
//GO(XML_SetDefaultHandler, 
//GO(XML_SetDefaultHandlerExpand, 
//GO(XML_SetDoctypeDeclHandler, 
//GO(XML_SetElementDeclHandler, 
GOM(XML_SetElementHandler, vFEppp)
//GO(XML_SetEncoding, 
//GO(XML_SetEndCdataSectionHandler, 
//GO(XML_SetEndDoctypeDeclHandler, 
//GO(XML_SetEndElementHandler, 
//GO(XML_SetEndNamespaceDeclHandler, 
//GO(XML_SetEntityDeclHandler, 
//GO(XML_SetExternalEntityRefHandler, 
//GO(XML_SetExternalEntityRefHandlerArg, 
//GO(XML_SetHashSalt, 
//GO(XML_SetNamespaceDeclHandler, 
//GO(XML_SetNotationDeclHandler, 
//GO(XML_SetNotStandaloneHandler, 
//GO(XML_SetParamEntityParsing, 
//GO(XML_SetProcessingInstructionHandler, 
//GO(XML_SetReturnNSTriplet, 
//GO(XML_SetSkippedEntityHandler, 
//GO(XML_SetStartCdataSectionHandler, 
//GO(XML_SetStartDoctypeDeclHandler, 
//GO(XML_SetStartElementHandler, 
//GO(XML_SetStartNamespaceDeclHandler, 
//GO(XML_SetUnknownEncodingHandler, 
//GO(XML_SetUnparsedEntityDeclHandler, 
GO(XML_SetUserData, vFpp)
//GO(XML_SetXmlDeclHandler, 
//GO(XML_StopParser, 
//GO(XML_UseForeignDTD, 
//GO(XML_UseParserAsHandlerArg, 
