#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

//GO(mbedtls_test_ca_crt
//GO(mbedtls_test_ca_key
//GO(mbedtls_test_ca_pwd
//GO(mbedtls_test_cas
//GO(mbedtls_test_cas_der
//GO(mbedtls_test_cli_crt
//GO(mbedtls_test_cli_key
//GO(mbedtls_test_cli_pwd
//GO(mbedtls_test_srv_crt
//GO(mbedtls_test_srv_key
//GO(mbedtls_test_srv_pwd
//GO(mbedtls_x509_crl_free
//GO(mbedtls_x509_crl_info
//GO(mbedtls_x509_crl_init
//GO(mbedtls_x509_crl_parse
//GO(mbedtls_x509_crl_parse_der
//GO(mbedtls_x509_crl_parse_file
//GO(mbedtls_x509_crt_check_extended_key_usage
//GO(mbedtls_x509_crt_check_key_usage
//GO(mbedtls_x509_crt_free
//GO(mbedtls_x509_crt_info
//GO(mbedtls_x509_crt_init
//GO(mbedtls_x509_crt_is_revoked
//GO(mbedtls_x509_crt_parse
//GO(mbedtls_x509_crt_parse_der
//GO(mbedtls_x509_crt_parse_der_nocopy
//GO(mbedtls_x509_crt_parse_der_with_ext_cb
//GO(mbedtls_x509_crt_parse_file
//GO(mbedtls_x509_crt_parse_path
//GO(mbedtls_x509_crt_verify
//GO(mbedtls_x509_crt_verify_info
//GO(mbedtls_x509_crt_verify_restartable
//GO(mbedtls_x509_crt_verify_with_profile
//GO(mbedtls_x509_csr_free
//GO(mbedtls_x509_csr_info
//GO(mbedtls_x509_csr_init
//GO(mbedtls_x509_csr_parse
//GO(mbedtls_x509_csr_parse_der
//GO(mbedtls_x509_csr_parse_file
//GO(mbedtls_x509_dn_gets
//GO(mbedtls_x509_get_alg
//GO(mbedtls_x509_get_alg_null
//GO(mbedtls_x509_get_ext
//GO(mbedtls_x509_get_name
//GO(mbedtls_x509_get_rsassa_pss_params
//GO(mbedtls_x509_get_serial
//GO(mbedtls_x509_get_sig
//GO(mbedtls_x509_get_sig_alg
//GO(mbedtls_x509_get_time
//GO(mbedtls_x509_key_size_helper
//GO(mbedtls_x509_parse_subject_alt_name
//GO(mbedtls_x509_self_test
//GO(mbedtls_x509_serial_gets
//GO(mbedtls_x509_set_extension
//GO(mbedtls_x509_sig_alg_gets
//GO(mbedtls_x509_string_to_names
//GO(mbedtls_x509_time_is_future
//GO(mbedtls_x509_time_is_past
//GO(mbedtls_x509write_crt_der
//GO(mbedtls_x509write_crt_free
//GO(mbedtls_x509write_crt_init
//GO(mbedtls_x509write_crt_pem
//GO(mbedtls_x509write_crt_set_authority_key_identifier
//GO(mbedtls_x509write_crt_set_basic_constraints
//GO(mbedtls_x509write_crt_set_extension
//GO(mbedtls_x509write_crt_set_issuer_key
//GO(mbedtls_x509write_crt_set_issuer_name
//GO(mbedtls_x509write_crt_set_key_usage
//GO(mbedtls_x509write_crt_set_md_alg
//GO(mbedtls_x509write_crt_set_ns_cert_type
//GO(mbedtls_x509write_crt_set_serial
//GO(mbedtls_x509write_crt_set_subject_key
//GO(mbedtls_x509write_crt_set_subject_key_identifier
//GO(mbedtls_x509write_crt_set_subject_name
//GO(mbedtls_x509write_crt_set_validity
//GO(mbedtls_x509write_crt_set_version
//GO(mbedtls_x509write_csr_der
//GO(mbedtls_x509write_csr_free
//GO(mbedtls_x509write_csr_init
//GO(mbedtls_x509write_csr_pem
//GO(mbedtls_x509write_csr_set_extension
//GO(mbedtls_x509write_csr_set_key
//GO(mbedtls_x509write_csr_set_key_usage
//GO(mbedtls_x509write_csr_set_md_alg
//GO(mbedtls_x509write_csr_set_ns_cert_type
//GO(mbedtls_x509write_csr_set_subject_name
//GO(mbedtls_x509_write_extensions
//GO(mbedtls_x509_write_names
//GO(mbedtls_x509_write_sig
