#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

//GO(pci_alloc, 
//GO(pci_cleanup, 
//GO(pci_fill_info, 
//GO(pci_filter_init, 
//GO(pci_filter_match, 
//GO(pci_filter_parse_id, 
//GO(pci_filter_parse_slot, 
//GO(pci_find_cap, 
//GO(pci_find_cap_nr, 
//GO(pci_free_dev, 
//GO(pci_free_name_list, 
//GO(pci_get_dev, 
//GO(pci_get_method_name, 
//GO(pci_get_param, 
//GO(pci_get_string_property, 
//GO(pci_id_cache_flush, 
//GO(pci_init, 
//GO(pci_load_name_list, 
//GO(pci_lookup_method, 
//GO(pci_lookup_name, 
//GO(pci_read_block, 
//GO(pci_read_byte, 
//GO(pci_read_long, 
//GO(pci_read_vpd, 
//GO(pci_read_word, 
//GO(pci_scan_bus, 
//GO(pci_set_name_list_path, 
//GO(pci_set_param, 
//GO(pci_setup_cache, 
//GO(pci_walk_params, 
//GO(pci_write_block, 
//GO(pci_write_byte, 
//GO(pci_write_long, 
//GO(pci_write_word, 
