#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

//GO(gst_fft_f32_fft, 
//GO(gst_fft_f32_free, 
//GO(gst_fft_f32_inverse_fft, 
//GO(gst_fft_f32_new, 
//GO(gst_fft_f32_window, 
//GO(gst_fft_f64_fft, 
//GO(gst_fft_f64_free, 
//GO(gst_fft_f64_inverse_fft, 
//GO(gst_fft_f64_new, 
//GO(gst_fft_f64_window, 
//GO(gst_fft_next_fast_length, 
//GO(gst_fft_s16_fft, 
//GO(gst_fft_s16_free, 
//GO(gst_fft_s16_inverse_fft, 
//GO(gst_fft_s16_new, 
//GO(gst_fft_s16_window, 
//GO(gst_fft_s32_fft, 
//GO(gst_fft_s32_free, 
//GO(gst_fft_s32_inverse_fft, 
//GO(gst_fft_s32_new, 
//GO(gst_fft_s32_window, 
