#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

//GO(mbedtls_aes_cmac_prf_128
//GO(mbedtls_aes_crypt_cbc
//GO(mbedtls_aes_crypt_cfb128
//GO(mbedtls_aes_crypt_cfb8
//GO(mbedtls_aes_crypt_ctr
//GO(mbedtls_aes_crypt_ecb
//GO(mbedtls_aes_crypt_ofb
//GO(mbedtls_aes_crypt_xts
//GO(mbedtls_aes_decrypt
//GO(mbedtls_aes_encrypt
//GO(mbedtls_aes_free
//GO(mbedtls_aes_init
//GO(mbedtls_aesni_crypt_ecb
//GO(mbedtls_aesni_gcm_mult
//GO(mbedtls_aesni_has_support
//GO(mbedtls_aesni_inverse_key
//GO(mbedtls_aesni_setkey_enc
//GO(mbedtls_aes_self_test
//GO(mbedtls_aes_setkey_dec
//GO(mbedtls_aes_setkey_enc
//GO(mbedtls_aes_xts_free
//GO(mbedtls_aes_xts_init
//GO(mbedtls_aes_xts_setkey_dec
//GO(mbedtls_aes_xts_setkey_enc
//GO(mbedtls_arc4_crypt
//GO(mbedtls_arc4_free
//GO(mbedtls_arc4_init
//GO(mbedtls_arc4_self_test
//GO(mbedtls_arc4_setup
//GO(mbedtls_asn1_find_named_data
//GO(mbedtls_asn1_free_named_data
//GO(mbedtls_asn1_free_named_data_list
//GO(mbedtls_asn1_get_alg
//GO(mbedtls_asn1_get_alg_null
//GO(mbedtls_asn1_get_bitstring
//GO(mbedtls_asn1_get_bitstring_null
//GO(mbedtls_asn1_get_bool
//GO(mbedtls_asn1_get_enum
//GO(mbedtls_asn1_get_int
//GO(mbedtls_asn1_get_len
//GO(mbedtls_asn1_get_mpi
//GO(mbedtls_asn1_get_sequence_of
//GO(mbedtls_asn1_get_tag
//GO(mbedtls_asn1_sequence_free
//GO(mbedtls_asn1_store_named_data
//GO(mbedtls_asn1_traverse_sequence_of
//GO(mbedtls_asn1_write_algorithm_identifier
//GO(mbedtls_asn1_write_bitstring
//GO(mbedtls_asn1_write_bool
//GO(mbedtls_asn1_write_enum
//GO(mbedtls_asn1_write_ia5_string
//GO(mbedtls_asn1_write_int
//GO(mbedtls_asn1_write_len
//GO(mbedtls_asn1_write_mpi
//GO(mbedtls_asn1_write_named_bitstring
//GO(mbedtls_asn1_write_null
//GO(mbedtls_asn1_write_octet_string
//GO(mbedtls_asn1_write_oid
//GO(mbedtls_asn1_write_printable_string
//GO(mbedtls_asn1_write_raw_buffer
//GO(mbedtls_asn1_write_tag
//GO(mbedtls_asn1_write_tagged_string
//GO(mbedtls_asn1_write_utf8_string
//GO(mbedtls_base64_decode
//GO(mbedtls_base64_encode
//GO(mbedtls_base64_self_test
//GO(mbedtls_blowfish_crypt_cbc
//GO(mbedtls_blowfish_crypt_cfb64
//GO(mbedtls_blowfish_crypt_ctr
//GO(mbedtls_blowfish_crypt_ecb
//GO(mbedtls_blowfish_free
//GO(mbedtls_blowfish_init
//GO(mbedtls_blowfish_setkey
//GO(mbedtls_camellia_crypt_cbc
//GO(mbedtls_camellia_crypt_cfb128
//GO(mbedtls_camellia_crypt_ctr
//GO(mbedtls_camellia_crypt_ecb
//GO(mbedtls_camellia_free
//GO(mbedtls_camellia_init
//GO(mbedtls_camellia_self_test
//GO(mbedtls_camellia_setkey_dec
//GO(mbedtls_camellia_setkey_enc
//GO(mbedtls_ccm_auth_decrypt
//GO(mbedtls_ccm_encrypt_and_tag
//GO(mbedtls_ccm_free
//GO(mbedtls_ccm_init
//GO(mbedtls_ccm_self_test
//GO(mbedtls_ccm_setkey
//GO(mbedtls_ccm_star_auth_decrypt
//GO(mbedtls_ccm_star_encrypt_and_tag
//GO(mbedtls_chacha20_crypt
//GO(mbedtls_chacha20_free
//GO(mbedtls_chacha20_init
//GO(mbedtls_chacha20_self_test
//GO(mbedtls_chacha20_setkey
//GO(mbedtls_chacha20_starts
//GO(mbedtls_chacha20_update
//GO(mbedtls_chachapoly_auth_decrypt
//GO(mbedtls_chachapoly_encrypt_and_tag
//GO(mbedtls_chachapoly_finish
//GO(mbedtls_chachapoly_free
//GO(mbedtls_chachapoly_init
//GO(mbedtls_chachapoly_self_test
//GO(mbedtls_chachapoly_setkey
//GO(mbedtls_chachapoly_starts
//GO(mbedtls_chachapoly_update
//GO(mbedtls_chachapoly_update_aad
//GO(mbedtls_cipher_auth_decrypt
//GO(mbedtls_cipher_auth_decrypt_ext
//GO(mbedtls_cipher_auth_encrypt
//GO(mbedtls_cipher_auth_encrypt_ext
//GO(mbedtls_cipher_check_tag
//GO(mbedtls_cipher_cmac
//GO(mbedtls_cipher_cmac_finish
//GO(mbedtls_cipher_cmac_reset
//GO(mbedtls_cipher_cmac_starts
//GO(mbedtls_cipher_cmac_update
//GO(mbedtls_cipher_crypt
//GO(mbedtls_cipher_definitions
//GO(mbedtls_cipher_finish
//GO(mbedtls_cipher_free
//GO(mbedtls_cipher_info_from_psa
//GO(mbedtls_cipher_info_from_string
//GO(mbedtls_cipher_info_from_type
//GO(mbedtls_cipher_info_from_values
//GO(mbedtls_cipher_init
//GO(mbedtls_cipher_list
//GO(mbedtls_cipher_reset
//GO(mbedtls_cipher_set_iv
//GO(mbedtls_cipher_setkey
//GO(mbedtls_cipher_set_padding_mode
//GO(mbedtls_cipher_setup
//GO(mbedtls_cipher_supported
//GO(mbedtls_cipher_update
//GO(mbedtls_cipher_update_ad
//GO(mbedtls_cipher_write_tag
//GO(mbedtls_cmac_self_test
//GO(mbedtls_ct_base64_dec_value
//GO(mbedtls_ct_base64_enc_char
//GO(mbedtls_ct_hmac
//GO(mbedtls_ct_memcmp
//GO(mbedtls_ct_memcpy_if_eq
//GO(mbedtls_ct_memcpy_offset
//GO(mbedtls_ct_mpi_uint_cond_assign
//GO(mbedtls_ct_mpi_uint_lt
//GO(mbedtls_ct_mpi_uint_mask
//GO(mbedtls_ctr_drbg_free
//GO(mbedtls_ctr_drbg_init
//GO(mbedtls_ctr_drbg_random
//GO(mbedtls_ctr_drbg_random_with_add
//GO(mbedtls_ctr_drbg_reseed
//GO(mbedtls_ctr_drbg_seed
//GO(mbedtls_ctr_drbg_self_test
//GO(mbedtls_ctr_drbg_set_entropy_len
//GO(mbedtls_ctr_drbg_set_nonce_len
//GO(mbedtls_ctr_drbg_set_prediction_resistance
//GO(mbedtls_ctr_drbg_set_reseed_interval
//GO(mbedtls_ctr_drbg_update
//GO(mbedtls_ctr_drbg_update_ret
//GO(mbedtls_ctr_drbg_update_seed_file
//GO(mbedtls_ctr_drbg_write_seed_file
//GO(mbedtls_ct_rsaes_pkcs1_v15_unpadding
//GO(mbedtls_ct_size_bool_eq
//GO(mbedtls_ct_size_mask
//GO(mbedtls_ct_size_mask_ge
//GO(mbedtls_ct_uint_if
//GO(mbedtls_ct_uint_mask
//GO(mbedtls_des3_crypt_cbc
//GO(mbedtls_des3_crypt_ecb
//GO(mbedtls_des3_free
//GO(mbedtls_des3_init
//GO(mbedtls_des3_set2key_dec
//GO(mbedtls_des3_set2key_enc
//GO(mbedtls_des3_set3key_dec
//GO(mbedtls_des3_set3key_enc
//GO(mbedtls_des_crypt_cbc
//GO(mbedtls_des_crypt_ecb
//GO(mbedtls_des_free
//GO(mbedtls_des_init
//GO(mbedtls_des_key_check_key_parity
//GO(mbedtls_des_key_check_weak
//GO(mbedtls_des_key_set_parity
//GO(mbedtls_des_self_test
//GO(mbedtls_des_setkey
//GO(mbedtls_des_setkey_dec
//GO(mbedtls_des_setkey_enc
//GO(mbedtls_dhm_calc_secret
//GO(mbedtls_dhm_free
//GO(mbedtls_dhm_init
//GO(mbedtls_dhm_make_params
//GO(mbedtls_dhm_make_public
//GO(mbedtls_dhm_parse_dhm
//GO(mbedtls_dhm_parse_dhmfile
//GO(mbedtls_dhm_read_params
//GO(mbedtls_dhm_read_public
//GO(mbedtls_dhm_self_test
//GO(mbedtls_dhm_set_group
//GO(mbedtls_ecc_group_of_psa
//GO(mbedtls_ecdh_calc_secret
//GO(mbedtls_ecdh_can_do
//GO(mbedtls_ecdh_compute_shared
//GO(mbedtls_ecdh_free
//GO(mbedtls_ecdh_gen_public
//GO(mbedtls_ecdh_get_params
//GO(mbedtls_ecdh_init
//GO(mbedtls_ecdh_make_params
//GO(mbedtls_ecdh_make_public
//GO(mbedtls_ecdh_read_params
//GO(mbedtls_ecdh_read_public
//GO(mbedtls_ecdh_setup
//GO(mbedtls_ecdsa_can_do
//GO(mbedtls_ecdsa_free
//GO(mbedtls_ecdsa_from_keypair
//GO(mbedtls_ecdsa_genkey
//GO(mbedtls_ecdsa_info
//GO(mbedtls_ecdsa_init
//GO(mbedtls_ecdsa_read_signature
//GO(mbedtls_ecdsa_read_signature_restartable
//GO(mbedtls_ecdsa_sign
//GO(mbedtls_ecdsa_sign_det
//GO(mbedtls_ecdsa_sign_det_ext
//GO(mbedtls_ecdsa_verify
//GO(mbedtls_ecdsa_write_signature
//GO(mbedtls_ecdsa_write_signature_det
//GO(mbedtls_ecdsa_write_signature_restartable
//GO(mbedtls_eckeydh_info
//GO(mbedtls_eckey_info
//GO(mbedtls_ecp_check_privkey
//GO(mbedtls_ecp_check_pubkey
//GO(mbedtls_ecp_check_pub_priv
//GO(mbedtls_ecp_copy
//GO(mbedtls_ecp_curve_info_from_grp_id
//GO(mbedtls_ecp_curve_info_from_name
//GO(mbedtls_ecp_curve_info_from_tls_id
//GO(mbedtls_ecp_curve_list
//GO(mbedtls_ecp_gen_key
//GO(mbedtls_ecp_gen_keypair
//GO(mbedtls_ecp_gen_keypair_base
//GO(mbedtls_ecp_gen_privkey
//GO(mbedtls_ecp_get_type
//GO(mbedtls_ecp_group_copy
//GO(mbedtls_ecp_group_free
//GO(mbedtls_ecp_group_init
//GO(mbedtls_ecp_group_load
//GO(mbedtls_ecp_grp_id_list
//GO(mbedtls_ecp_is_zero
//GO(mbedtls_ecp_keypair_free
//GO(mbedtls_ecp_keypair_init
//GO(mbedtls_ecp_mul
//GO(mbedtls_ecp_muladd
//GO(mbedtls_ecp_muladd_restartable
//GO(mbedtls_ecp_mul_restartable
//GO(mbedtls_ecp_point_cmp
//GO(mbedtls_ecp_point_free
//GO(mbedtls_ecp_point_init
//GO(mbedtls_ecp_point_read_binary
//GO(mbedtls_ecp_point_read_string
//GO(mbedtls_ecp_point_write_binary
//GO(mbedtls_ecp_read_key
//GO(mbedtls_ecp_self_test
//GO(mbedtls_ecp_set_zero
//GO(mbedtls_ecp_tls_read_group
//GO(mbedtls_ecp_tls_read_group_id
//GO(mbedtls_ecp_tls_read_point
//GO(mbedtls_ecp_tls_write_group
//GO(mbedtls_ecp_tls_write_point
//GO(mbedtls_ecp_write_key
//GO(mbedtls_entropy_add_source
//GO(mbedtls_entropy_free
//GO(mbedtls_entropy_func
//GO(mbedtls_entropy_gather
//GO(mbedtls_entropy_init
//GO(mbedtls_entropy_self_test
//GO(mbedtls_entropy_update_manual
//GO(mbedtls_entropy_update_seed_file
//GO(mbedtls_entropy_write_seed_file
//GO(mbedtls_gcm_auth_decrypt
//GO(mbedtls_gcm_crypt_and_tag
//GO(mbedtls_gcm_finish
//GO(mbedtls_gcm_free
//GO(mbedtls_gcm_init
//GO(mbedtls_gcm_self_test
//GO(mbedtls_gcm_setkey
//GO(mbedtls_gcm_starts
//GO(mbedtls_gcm_update
//GO(mbedtls_hardclock_poll
//GO(mbedtls_havege_free
//GO(mbedtls_havege_init
//GO(mbedtls_havege_poll
//GO(mbedtls_havege_random
//GO(mbedtls_high_level_strerr
//GO(mbedtls_hkdf
//GO(mbedtls_hkdf_expand
//GO(mbedtls_hkdf_extract
//GO(mbedtls_hmac_drbg_free
//GO(mbedtls_hmac_drbg_init
//GO(mbedtls_hmac_drbg_random
//GO(mbedtls_hmac_drbg_random_with_add
//GO(mbedtls_hmac_drbg_reseed
//GO(mbedtls_hmac_drbg_seed
//GO(mbedtls_hmac_drbg_seed_buf
//GO(mbedtls_hmac_drbg_self_test
//GO(mbedtls_hmac_drbg_set_entropy_len
//GO(mbedtls_hmac_drbg_set_prediction_resistance
//GO(mbedtls_hmac_drbg_set_reseed_interval
//GO(mbedtls_hmac_drbg_update
//GO(mbedtls_hmac_drbg_update_ret
//GO(mbedtls_hmac_drbg_update_seed_file
//GO(mbedtls_hmac_drbg_write_seed_file
//GO(mbedtls_internal_aes_decrypt
//GO(mbedtls_internal_aes_encrypt
//GO(mbedtls_internal_md2_process
//GO(mbedtls_internal_md4_process
//GO(mbedtls_internal_md5_process
//GO(mbedtls_internal_ripemd160_process
//GO(mbedtls_internal_sha1_process
//GO(mbedtls_internal_sha256_process
//GO(mbedtls_internal_sha512_process
//GO(mbedtls_low_level_strerr
//GO(mbedtls_md
//GO(mbedtls_md2
//GO(mbedtls_md2_clone
//GO(mbedtls_md2_finish
//GO(mbedtls_md2_finish_ret
//GO(mbedtls_md2_free
//GO(mbedtls_md2_info
//GO(mbedtls_md2_init
//GO(mbedtls_md2_process
//GO(mbedtls_md2_ret
//GO(mbedtls_md2_self_test
//GO(mbedtls_md2_starts
//GO(mbedtls_md2_starts_ret
//GO(mbedtls_md2_update
//GO(mbedtls_md2_update_ret
//GO(mbedtls_md4
//GO(mbedtls_md4_clone
//GO(mbedtls_md4_finish
//GO(mbedtls_md4_finish_ret
//GO(mbedtls_md4_free
//GO(mbedtls_md4_info
//GO(mbedtls_md4_init
//GO(mbedtls_md4_process
//GO(mbedtls_md4_ret
//GO(mbedtls_md4_self_test
//GO(mbedtls_md4_starts
//GO(mbedtls_md4_starts_ret
//GO(mbedtls_md4_update
//GO(mbedtls_md4_update_ret
//GO(mbedtls_md5
//GO(mbedtls_md5_clone
//GO(mbedtls_md5_finish
//GO(mbedtls_md5_finish_ret
//GO(mbedtls_md5_free
//GO(mbedtls_md5_info
//GO(mbedtls_md5_init
//GO(mbedtls_md5_process
//GO(mbedtls_md5_ret
//GO(mbedtls_md5_self_test
//GO(mbedtls_md5_starts
//GO(mbedtls_md5_starts_ret
//GO(mbedtls_md5_update
//GO(mbedtls_md5_update_ret
//GO(mbedtls_md_clone
//GO(mbedtls_md_file
//GO(mbedtls_md_finish
//GO(mbedtls_md_free
//GO(mbedtls_md_get_name
//GO(mbedtls_md_get_size
//GO(mbedtls_md_get_type
//GO(mbedtls_md_hmac
//GO(mbedtls_md_hmac_finish
//GO(mbedtls_md_hmac_reset
//GO(mbedtls_md_hmac_starts
//GO(mbedtls_md_hmac_update
//GO(mbedtls_md_info_from_psa
//GO(mbedtls_md_info_from_string
//GO(mbedtls_md_info_from_type
//GO(mbedtls_md_init
//GO(mbedtls_md_init_ctx
//GO(mbedtls_md_list
//GO(mbedtls_md_process
//GO(mbedtls_md_setup
//GO(mbedtls_md_starts
//GO(mbedtls_md_update
//GO(mbedtls_mpi_add_abs
//GO(mbedtls_mpi_add_int
//GO(mbedtls_mpi_add_mpi
//GO(mbedtls_mpi_bitlen
//GO(mbedtls_mpi_cmp_abs
//GO(mbedtls_mpi_cmp_int
//GO(mbedtls_mpi_cmp_mpi
//GO(mbedtls_mpi_copy
//GO(mbedtls_mpi_div_int
//GO(mbedtls_mpi_div_mpi
//GO(mbedtls_mpi_exp_mod
//GO(mbedtls_mpi_fill_random
//GO(mbedtls_mpi_free
//GO(mbedtls_mpi_gcd
//GO(mbedtls_mpi_gen_prime
//GO(mbedtls_mpi_get_bit
//GO(mbedtls_mpi_grow
//GO(mbedtls_mpi_init
//GO(mbedtls_mpi_inv_mod
//GO(mbedtls_mpi_is_prime
//GO(mbedtls_mpi_is_prime_ext
//GO(mbedtls_mpi_lsb
//GO(mbedtls_mpi_lset
//GO(mbedtls_mpi_lt_mpi_ct
//GO(mbedtls_mpi_mod_int
//GO(mbedtls_mpi_mod_mpi
//GO(mbedtls_mpi_mul_int
//GO(mbedtls_mpi_mul_mpi
//GO(mbedtls_mpi_random
//GO(mbedtls_mpi_read_binary
//GO(mbedtls_mpi_read_binary_le
//GO(mbedtls_mpi_read_file
//GO(mbedtls_mpi_read_string
//GO(mbedtls_mpi_safe_cond_assign
//GO(mbedtls_mpi_safe_cond_swap
//GO(mbedtls_mpi_self_test
//GO(mbedtls_mpi_set_bit
//GO(mbedtls_mpi_shift_l
//GO(mbedtls_mpi_shift_r
//GO(mbedtls_mpi_shrink
//GO(mbedtls_mpi_size
//GO(mbedtls_mpi_sub_abs
//GO(mbedtls_mpi_sub_int
//GO(mbedtls_mpi_sub_mpi
//GO(mbedtls_mpi_swap
//GO(mbedtls_mpi_write_binary
//GO(mbedtls_mpi_write_binary_le
//GO(mbedtls_mpi_write_file
//GO(mbedtls_mpi_write_string
//GO(mbedtls_mutex_free
//GO(mbedtls_mutex_init
//GO(mbedtls_mutex_lock
//GO(mbedtls_mutex_unlock
//GO(mbedtls_oid_get_attr_short_name
//GO(mbedtls_oid_get_certificate_policies
//GO(mbedtls_oid_get_cipher_alg
//GO(mbedtls_oid_get_ec_grp
//GO(mbedtls_oid_get_extended_key_usage
//GO(mbedtls_oid_get_md_alg
//GO(mbedtls_oid_get_md_hmac
//GO(mbedtls_oid_get_numeric_string
//GO(mbedtls_oid_get_oid_by_ec_grp
//GO(mbedtls_oid_get_oid_by_md
//GO(mbedtls_oid_get_oid_by_pk_alg
//GO(mbedtls_oid_get_oid_by_sig_alg
//GO(mbedtls_oid_get_pk_alg
//GO(mbedtls_oid_get_pkcs12_pbe_alg
//GO(mbedtls_oid_get_sig_alg
//GO(mbedtls_oid_get_sig_alg_desc
//GO(mbedtls_oid_get_x509_ext_type
//GO(mbedtls_pem_free
//GO(mbedtls_pem_init
//GO(mbedtls_pem_read_buffer
//GO(mbedtls_pem_write_buffer
//GO(mbedtls_pk_can_do
//GO(mbedtls_pk_check_pair
//GO(mbedtls_pkcs12_derivation
//GO(mbedtls_pkcs12_pbe
//GO(mbedtls_pkcs12_pbe_sha1_rc4_128
//GO(mbedtls_pkcs5_pbes2
//GO(mbedtls_pkcs5_pbkdf2_hmac
//GO(mbedtls_pkcs5_self_test
//GO(mbedtls_pk_debug
//GO(mbedtls_pk_decrypt
//GO(mbedtls_pk_encrypt
//GO(mbedtls_pk_free
//GO(mbedtls_pk_get_bitlen
//GO(mbedtls_pk_get_name
//GO(mbedtls_pk_get_type
//GO(mbedtls_pk_info_from_type
//GO(mbedtls_pk_init
//GO(mbedtls_pk_load_file
//GO(mbedtls_pk_parse_key
//GO(mbedtls_pk_parse_keyfile
//GO(mbedtls_pk_parse_public_key
//GO(mbedtls_pk_parse_public_keyfile
//GO(mbedtls_pk_parse_subpubkey
//GO(mbedtls_pk_setup
//GO(mbedtls_pk_setup_rsa_alt
//GO(mbedtls_pk_sign
//GO(mbedtls_pk_sign_restartable
//GO(mbedtls_pk_verify
//GO(mbedtls_pk_verify_ext
//GO(mbedtls_pk_verify_restartable
//GO(mbedtls_pk_write_key_der
//GO(mbedtls_pk_write_key_pem
//GO(mbedtls_pk_write_pubkey
//GO(mbedtls_pk_write_pubkey_der
//GO(mbedtls_pk_write_pubkey_pem
//GO(mbedtls_platform_entropy_poll
//GO(mbedtls_platform_gmtime_r
//GO(mbedtls_platform_setup
//GO(mbedtls_platform_teardown
//GO(mbedtls_platform_zeroize
//GO(mbedtls_poly1305_finish
//GO(mbedtls_poly1305_free
//GO(mbedtls_poly1305_init
//GO(mbedtls_poly1305_mac
//GO(mbedtls_poly1305_self_test
//GO(mbedtls_poly1305_starts
//GO(mbedtls_poly1305_update
//GO(mbedtls_psa_aead_decrypt
//GO(mbedtls_psa_aead_encrypt
//GO(mbedtls_psa_cipher_abort
//GO(mbedtls_psa_cipher_decrypt
//GO(mbedtls_psa_cipher_decrypt_setup
//GO(mbedtls_psa_cipher_encrypt
//GO(mbedtls_psa_cipher_encrypt_setup
//GO(mbedtls_psa_cipher_finish
//GO(mbedtls_psa_cipher_set_iv
//GO(mbedtls_psa_cipher_update
//GO(mbedtls_psa_crypto_configure_entropy_sources
//GO(mbedtls_psa_crypto_free
//GO(mbedtls_psa_ecdsa_sign_hash
//GO(mbedtls_psa_ecdsa_verify_hash
//GO(mbedtls_psa_ecp_export_key
//GO(mbedtls_psa_ecp_export_public_key
//GO(mbedtls_psa_ecp_generate_key
//GO(mbedtls_psa_ecp_import_key
//GO(mbedtls_psa_ecp_load_representation
//GO(mbedtls_psa_get_stats
//GO(mbedtls_psa_hash_abort
//GO(mbedtls_psa_hash_clone
//GO(mbedtls_psa_hash_compute
//GO(mbedtls_psa_hash_finish
//GO(mbedtls_psa_hash_setup
//GO(mbedtls_psa_hash_update
//GO(mbedtls_psa_mac_abort
//GO(mbedtls_psa_mac_compute
//GO(mbedtls_psa_mac_sign_finish
//GO(mbedtls_psa_mac_sign_setup
//GO(mbedtls_psa_mac_update
//GO(mbedtls_psa_mac_verify_finish
//GO(mbedtls_psa_mac_verify_setup
//GO(mbedtls_psa_random_state
//GO(mbedtls_psa_rsa_export_key
//GO(mbedtls_psa_rsa_export_public_key
//GO(mbedtls_psa_rsa_generate_key
//GO(mbedtls_psa_rsa_import_key
//GO(mbedtls_psa_rsa_load_representation
//GO(mbedtls_psa_rsa_sign_hash
//GO(mbedtls_psa_rsa_verify_hash
//GO(mbedtls_ripemd160
//GO(mbedtls_ripemd160_clone
//GO(mbedtls_ripemd160_finish
//GO(mbedtls_ripemd160_finish_ret
//GO(mbedtls_ripemd160_free
//GO(mbedtls_ripemd160_info
//GO(mbedtls_ripemd160_init
//GO(mbedtls_ripemd160_process
//GO(mbedtls_ripemd160_ret
//GO(mbedtls_ripemd160_self_test
//GO(mbedtls_ripemd160_starts
//GO(mbedtls_ripemd160_starts_ret
//GO(mbedtls_ripemd160_update
//GO(mbedtls_ripemd160_update_ret
//GO(mbedtls_rsa_alt_info
//GO(mbedtls_rsa_check_privkey
//GO(mbedtls_rsa_check_pubkey
//GO(mbedtls_rsa_check_pub_priv
//GO(mbedtls_rsa_complete
//GO(mbedtls_rsa_copy
//GO(mbedtls_rsa_deduce_crt
//GO(mbedtls_rsa_deduce_primes
//GO(mbedtls_rsa_deduce_private_exponent
//GO(mbedtls_rsa_export
//GO(mbedtls_rsa_export_crt
//GO(mbedtls_rsa_export_raw
//GO(mbedtls_rsa_free
//GO(mbedtls_rsa_gen_key
//GO(mbedtls_rsa_get_len
//GO(mbedtls_rsa_import
//GO(mbedtls_rsa_import_raw
//GO(mbedtls_rsa_info
//GO(mbedtls_rsa_init
//GO(mbedtls_rsa_pkcs1_decrypt
//GO(mbedtls_rsa_pkcs1_encrypt
//GO(mbedtls_rsa_pkcs1_sign
//GO(mbedtls_rsa_pkcs1_verify
//GO(mbedtls_rsa_private
//GO(mbedtls_rsa_public
//GO(mbedtls_rsa_rsaes_oaep_decrypt
//GO(mbedtls_rsa_rsaes_oaep_encrypt
//GO(mbedtls_rsa_rsaes_pkcs1_v15_decrypt
//GO(mbedtls_rsa_rsaes_pkcs1_v15_encrypt
//GO(mbedtls_rsa_rsassa_pkcs1_v15_sign
//GO(mbedtls_rsa_rsassa_pkcs1_v15_verify
//GO(mbedtls_rsa_rsassa_pss_sign
//GO(mbedtls_rsa_rsassa_pss_sign_ext
//GO(mbedtls_rsa_rsassa_pss_verify
//GO(mbedtls_rsa_rsassa_pss_verify_ext
//GO(mbedtls_rsa_self_test
//GO(mbedtls_rsa_set_padding
//GO(mbedtls_rsa_validate_crt
//GO(mbedtls_rsa_validate_params
//GO(mbedtls_set_alarm
//GO(mbedtls_sha1
//GO(mbedtls_sha1_clone
//GO(mbedtls_sha1_finish
//GO(mbedtls_sha1_finish_ret
//GO(mbedtls_sha1_free
//GO(mbedtls_sha1_info
//GO(mbedtls_sha1_init
//GO(mbedtls_sha1_process
//GO(mbedtls_sha1_ret
//GO(mbedtls_sha1_self_test
//GO(mbedtls_sha1_starts
//GO(mbedtls_sha1_starts_ret
//GO(mbedtls_sha1_update
//GO(mbedtls_sha1_update_ret
//GO(mbedtls_sha224_info
//GO(mbedtls_sha256
//GO(mbedtls_sha256_clone
//GO(mbedtls_sha256_finish
//GO(mbedtls_sha256_finish_ret
//GO(mbedtls_sha256_free
//GO(mbedtls_sha256_info
//GO(mbedtls_sha256_init
//GO(mbedtls_sha256_process
//GO(mbedtls_sha256_ret
//GO(mbedtls_sha256_self_test
//GO(mbedtls_sha256_starts
//GO(mbedtls_sha256_starts_ret
//GO(mbedtls_sha256_update
//GO(mbedtls_sha256_update_ret
//GO(mbedtls_sha384_info
//GO(mbedtls_sha512
//GO(mbedtls_sha512_clone
//GO(mbedtls_sha512_finish
//GO(mbedtls_sha512_finish_ret
//GO(mbedtls_sha512_free
//GO(mbedtls_sha512_info
//GO(mbedtls_sha512_init
//GO(mbedtls_sha512_process
//GO(mbedtls_sha512_ret
//GO(mbedtls_sha512_self_test
//GO(mbedtls_sha512_starts
//GO(mbedtls_sha512_starts_ret
//GO(mbedtls_sha512_update
//GO(mbedtls_sha512_update_ret
//GO(mbedtls_strerror
//GO(mbedtls_threading_readdir_mutex
//GO(mbedtls_timing_alarmed
//GO(mbedtls_timing_get_delay
//GO(mbedtls_timing_get_timer
//GO(mbedtls_timing_hardclock
//GO(mbedtls_timing_self_test
//GO(mbedtls_timing_set_delay
//GO(mbedtls_to_psa_error
//GO(mbedtls_version_check_feature
//GO(mbedtls_version_get_number
//GO(mbedtls_version_get_string
//GO(mbedtls_version_get_string_full
//GO(mbedtls_xtea_crypt_cbc
//GO(mbedtls_xtea_crypt_ecb
//GO(mbedtls_xtea_free
//GO(mbedtls_xtea_init
//GO(mbedtls_xtea_self_test
//GO(mbedtls_xtea_setup
//GO(psa_aead_decrypt
//GO(psa_aead_encrypt
//GO(psa_allocate_buffer_to_slot
//GO(psa_asymmetric_decrypt
//GO(psa_asymmetric_encrypt
//GO(psa_cipher_abort
//GO(psa_cipher_decrypt
//GO(psa_cipher_decrypt_setup
//GO(psa_cipher_encrypt
//GO(psa_cipher_encrypt_setup
//GO(psa_cipher_finish
//GO(psa_cipher_generate_iv
//GO(psa_cipher_set_iv
//GO(psa_cipher_update
//GO(psa_close_key
//GO(psa_copy_key
//GO(psa_copy_key_material_into_slot
//GO(psa_crypto_init
//GO(psa_destroy_key
//GO(psa_destroy_persistent_key
//GO(psa_driver_wrapper_aead_decrypt
//GO(psa_driver_wrapper_aead_encrypt
//GO(psa_driver_wrapper_cipher_abort
//GO(psa_driver_wrapper_cipher_decrypt
//GO(psa_driver_wrapper_cipher_decrypt_setup
//GO(psa_driver_wrapper_cipher_encrypt
//GO(psa_driver_wrapper_cipher_encrypt_setup
//GO(psa_driver_wrapper_cipher_finish
//GO(psa_driver_wrapper_cipher_set_iv
//GO(psa_driver_wrapper_cipher_update
//GO(psa_driver_wrapper_export_key
//GO(psa_driver_wrapper_export_public_key
//GO(psa_driver_wrapper_free
//GO(psa_driver_wrapper_generate_key
//GO(psa_driver_wrapper_get_builtin_key
//GO(psa_driver_wrapper_get_key_buffer_size
//GO(psa_driver_wrapper_hash_abort
//GO(psa_driver_wrapper_hash_clone
//GO(psa_driver_wrapper_hash_compute
//GO(psa_driver_wrapper_hash_finish
//GO(psa_driver_wrapper_hash_setup
//GO(psa_driver_wrapper_hash_update
//GO(psa_driver_wrapper_import_key
//GO(psa_driver_wrapper_init
//GO(psa_driver_wrapper_mac_abort
//GO(psa_driver_wrapper_mac_compute
//GO(psa_driver_wrapper_mac_sign_finish
//GO(psa_driver_wrapper_mac_sign_setup
//GO(psa_driver_wrapper_mac_update
//GO(psa_driver_wrapper_mac_verify_finish
//GO(psa_driver_wrapper_mac_verify_setup
//GO(psa_driver_wrapper_sign_hash
//GO(psa_driver_wrapper_sign_message
//GO(psa_driver_wrapper_verify_hash
//GO(psa_driver_wrapper_verify_message
//GO(psa_export_key
//GO(psa_export_key_internal
//GO(psa_export_public_key
//GO(psa_export_public_key_internal
//GO(psa_format_key_data_for_storage
//GO(psa_free_persistent_key_data
//GO(psa_generate_key
//GO(psa_generate_key_internal
//GO(psa_generate_random
//GO(psa_get_and_lock_key_slot
//GO(psa_get_empty_key_slot
//GO(psa_get_key_attributes
//GO(psa_get_key_domain_parameters
//GO(psa_hash_abort
//GO(psa_hash_clone
//GO(psa_hash_compare
//GO(psa_hash_compute
//GO(psa_hash_finish
//GO(psa_hash_setup
//GO(psa_hash_update
//GO(psa_hash_verify
//GO(psa_import_key
//GO(psa_import_key_into_slot
//GO(psa_initialize_key_slots
//GO(psa_is_key_present_in_storage
//GO(psa_is_valid_key_id
//GO(psa_its_get
//GO(psa_its_get_info
//GO(psa_its_remove
//GO(psa_its_set
//GO(psa_key_derivation_abort
//GO(psa_key_derivation_get_capacity
//GO(psa_key_derivation_input_bytes
//GO(psa_key_derivation_input_key
//GO(psa_key_derivation_key_agreement
//GO(psa_key_derivation_output_bytes
//GO(psa_key_derivation_output_key
//GO(psa_key_derivation_set_capacity
//GO(psa_key_derivation_setup
//GO(psa_load_persistent_key
//GO(psa_mac_abort
//GO(psa_mac_compute
//GO(psa_mac_sign_finish
//GO(psa_mac_sign_setup
//GO(psa_mac_update
//GO(psa_mac_verify
//GO(psa_mac_verify_finish
//GO(psa_mac_verify_setup
//GO(psa_open_key
//GO(psa_parse_key_data_from_storage
//GO(psa_purge_key
//GO(psa_raw_key_agreement
//GO(psa_remove_key_data_from_memory
//GO(psa_reset_key_attributes
//GO(psa_save_persistent_key
//GO(psa_set_key_domain_parameters
//GO(psa_sign_hash
//GO(psa_sign_hash_builtin
//GO(psa_sign_message
//GO(psa_sign_message_builtin
//GO(psa_unlock_key_slot
//GO(psa_validate_key_location
//GO(psa_validate_key_persistence
//GO(psa_verify_hash
//GO(psa_verify_hash_builtin
//GO(psa_verify_message
//GO(psa_verify_message_builtin
//GO(psa_wipe_all_key_slots
//GO(psa_wipe_key_slot
