#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(GOS))
#error Meh...
#endif

//GO(a64l, 
//GO(abort, 
//DATAB(__abort_msg, 
//GO(abs, 
//GO(accept, 
//GO(accept4, 
GOW(access, iFpi)
//GO(acct, 
//GOW(addmntent, 
//GOW(addseverity, 
//GOW(adjtime, 
//GO(__adjtimex, 
//GOW(adjtimex, 
//GOW(advance, 
//GO(alarm, 
//GOW(aligned_alloc, 
//GOW(alphasort, 
//GOW(alphasort64, 
//GO(__arch_prctl, 
//GOW(arch_prctl, 
//DATA(argp_err_exit_status, 
//GOW(argp_error, 
//GOW(argp_failure, 
//GOW(argp_help, 
//GOW(argp_parse, 
//DATAB(argp_program_bug_address, 
//DATAB(argp_program_version, 
//DATAB(argp_program_version_hook, 
//GOW(argp_state_help, 
//GOW(argp_usage, 
//GOW(argz_add, 
//GOW(argz_add_sep, 
//GOW(argz_append, 
//GO(__argz_count, 
//GOW(argz_count, 
//GOW(argz_create, 
//GOW(argz_create_sep, 
//GO(argz_delete, 
//GOW(argz_extract, 
//GOW(argz_insert, 
//GO(__argz_next, 
//GOW(argz_next, 
//GOW(argz_replace, 
//GO(__argz_stringify, 
//GOW(argz_stringify, 
//GO(asctime, 
//GOW(asctime_r, 
//GO(__asprintf, 
//GOW(asprintf, 
//GO(__asprintf_chk, 
//GO(__assert, 
//GO(__assert_fail, 
//GO(__assert_perror_fail, 
GO(atof, dFp)
GO(atoi, iFp)
GO(atol, lFp)
GO(atoll, IFp)
//GO(authdes_create, 
//GO(authdes_getucred, 
//GO(authdes_pk_create, 
//GO(_authenticate, 
//GO(authnone_create, 
//GO(authunix_create, 
//GO(authunix_create_default, 
//GO(__backtrace, 
//GOW(backtrace, 
//GO(__backtrace_symbols, 
//GOW(backtrace_symbols, 
//GO(__backtrace_symbols_fd, 
//GOW(backtrace_symbols_fd, 
//GOW(basename, 
//GOI(bcmp, 
//GO(bcopy, 
//GO(bdflush, 
//GOW(bind, 
//GO(bindresvport, 
//GOW(bindtextdomain, 
//GOW(bind_textdomain_codeset, 
//GOW(brk, 
//GO(__bsd_getpgrp, 
//GOW(bsd_signal, 
//GO(bsearch, 
GOW(btowc, iFi)
//GO(__bzero, 
//GOW(bzero, 
//GO(c16rtomb, 
//GOW(c32rtomb, 
GOW(calloc, pFLL)
//GO(callrpc, 
//GO(__call_tls_dtors, 
//GOW(canonicalize_file_name, 
//GO(capget, 
//GO(capset, 
//GO(catclose, 
//GO(catgets, 
//GO(catopen, 
//GO(cbc_crypt, 
//GO(cfgetispeed, 
//GO(cfgetospeed, 
//GO(cfmakeraw, 
//GO(cfree, 
//GO(cfsetispeed, 
//GO(cfsetospeed, 
//GO(cfsetspeed, 
//GOW(chdir, 
//DATA(__check_rhosts_file, 
//GO(chflags, 
//GO(__chk_fail, 
//GOW(chmod, 
//GOW(chown, 
//GO(chroot, 
//GOW(clearenv, 
//GO(clearerr, 
//GO(clearerr_unlocked, 
//GO(clnt_broadcast, 
//GO(clnt_create, 
//GO(clnt_pcreateerror, 
//GO(clnt_perrno, 
//GO(clnt_perror, 
//GO(clntraw_create, 
//GO(clnt_spcreateerror, 
//GO(clnt_sperrno, 
//GO(clnt_sperror, 
//GO(clnttcp_create, 
//GO(clntudp_bufcreate, 
//GO(clntudp_create, 
//GO(clntunix_create, 
GO(clock, LFv)
//GO(clock_adjtime, 
//GO(__clock_getcpuclockid, 
//GOW(clock_getcpuclockid, 
//GO(__clock_getres, 
//GOW(clock_getres, 
//GO(__clock_gettime, 
//GOW(clock_gettime, 
//GO(__clock_nanosleep, 
//GOW(clock_nanosleep, 
//GO(__clock_settime, 
//GOW(clock_settime, 
//GO(__clone, 
//GOW(clone, 
//GO(__close, 
GOW(close, iFi)
GOW(closedir, iFp)
GO(closelog, vFv)
//GO(__close_nocancel, 
//GO(__cmsg_nxthdr, 
//GO(confstr, 
//GO(__confstr_chk, 
//GOW(__connect, 
//GOW(connect, 
//GO(copy_file_range, 
//GO(__copy_grp, 
//GOW(copysign, 
//GOW(copysignf, 
//GOW(copysignl, 
//GOW(creat, 
//GOW(creat64, 
//GO(create_module, 
//GO(ctermid, 
//GO(ctime, 
//GO(ctime_r, 
//DATA(__ctype32_b, 
//DATA(__ctype32_tolower, 
//DATA(__ctype32_toupper, 
//DATA(__ctype_b, 
//GO(__ctype_b_loc, 
//GOW(__ctype_get_mb_cur_max, 
//GO(__ctype_init, 
//DATA(__ctype_tolower, 
//GO(__ctype_tolower_loc, 
//DATA(__ctype_toupper, 
//GO(__ctype_toupper_loc, 
//DATAB(__curbrk, 
//GO(cuserid, 
GOM(__cxa_atexit, iFEppp)
//GO(__cxa_at_quick_exit, 
GOM(__cxa_finalize, vFEp)
//GO(__cxa_thread_atexit_impl, 
//GO(__cyg_profile_func_enter, 
//GO(__cyg_profile_func_exit, 
//GO(daemon, 
//DATAB(__daylight, 
//GO(__dcgettext, 
//GOW(dcgettext, 
//GOW(dcngettext, 
//GO(__default_morecore, 
//GO(delete_module, 
//GO(des_setparity, 
//GO(__dgettext, 
//GOW(dgettext, 
//GO(difftime, 
//GO(dirfd, 
//GO(dirname, 
//GO(div, 
//GO(_dl_addr, 
//GO(_dl_catch_error, 
//GO(_dl_catch_exception, 
GOM(dl_iterate_phdr, iFEpp) //Weak
//GO(_dl_mcount_wrapper, 
//GO(_dl_mcount_wrapper_check, 
//DATAB(_dl_open_hook, 
//DATAB(_dl_open_hook2, 
//GO(_dl_signal_error, 
//GO(_dl_signal_exception, 
//GO(_dl_sym, 
//GO(_dl_vsym, 
//GOW(dngettext, 
//GO(dprintf, 
//GO(__dprintf_chk, 
//GO(drand48, 
//GO(drand48_r, 
//GOW(dup, 
//GO(__dup2, 
//GOW(dup2, 
//GOW(dup3, 
//GO(__duplocale, 
//GOW(duplocale, 
//GO(dysize, 
//GOW(eaccess, 
//GO(ecb_crypt, 
//GO(ecvt, 
//GOW(ecvt_r, 
//GO(endaliasent, 
//GO(endfsent, 
//GO(endgrent, 
//GO(endhostent, 
//GO(__endmntent, 
//GOW(endmntent, 
//GO(endnetent, 
//GO(endnetgrent, 
//GO(endprotoent, 
//GO(endpwent, 
//GO(endrpcent, 
//GO(endservent, 
//GO(endsgent, 
//GO(endspent, 
//GOW(endttyent, 
//GO(endusershell, 
//GOW(endutent, 
//GO(endutxent, 
//DATAB(__environ, 
//GO(envz_add, 
//GO(envz_entry, 
//GO(envz_get, 
//GO(envz_merge, 
//GO(envz_remove, 
//GO(envz_strip, 
//GO(epoll_create, 
//GO(epoll_create1, 
//GO(epoll_ctl, 
//GO(epoll_pwait, 
//GO(epoll_wait, 
//GO(erand48, 
//GOW(erand48_r, 
//GO(err, 
//DATAB(errno, 
GO(__errno_location, pFv)
//GOW(error, 
//GOW(error_at_line, 
//DATAB(error_message_count, 
//DATAB(error_one_per_line, 
//DATAB(error_print_progname, 
//GO(errx, 
//GO(ether_aton, 
//GO(ether_aton_r, 
//GO(ether_hostton, 
//GO(ether_line, 
//GO(ether_ntoa, 
//GO(ether_ntoa_r, 
//GO(ether_ntohost, 
//GOW(euidaccess, 
//GO(eventfd, 
//GO(eventfd_read, 
//GO(eventfd_write, 
//GO(execl, 
//GO(execle, 
GOM(execlp, iFEpV)
//GO(execv, 
//GOW(execve, 
GOM(execvp, iFEp)
//GOW(execvpe, 
GO(_exit, vFi)
GO(exit, vFi)
GOW(_Exit, vFi)
//GO(explicit_bzero, 
//GO(__explicit_bzero_chk, 
//GO(faccessat, 
//GOW(fallocate, 
//GO(fallocate64, 
//GO(fanotify_init, 
//GO(fanotify_mark, 
//GO(fattach, 
//GO(__fbufsize, 
//GOW(fchdir, 
//GO(fchflags, 
//GOW(fchmod, 
//GO(fchmodat, 
//GOW(fchown, 
//GO(fchownat, 
GO(fclose, iFp)
GOW(fcloseall, iFv)
GOM(__fcntl, iFEiiN)    //Weak
GOM(fcntl, iFEiiN)      //Weak
GOM(fcntl64, iFEiiN)    //Weak
//GO(fcvt, 
//GOW(fcvt_r, 
//GO(fdatasync, 
//GO(__fdelt_chk, 
//GO(__fdelt_warn, 
//GO(fdetach, 
//GO(fdopen, 
//GOW(fdopendir, 
//GO(__fentry__, 
//GOW(feof, 
//GOW(feof_unlocked, 
//GOW(ferror, 
//GOW(ferror_unlocked, 
//GO(fexecve, 
GOW(fflush, iFp)
GO(fflush_unlocked, iFp)
//GO(__ffs, 
//GO(ffs, 
//GOW(ffsl, 
//GO(ffsll, 
//GOW(fgetc, 
//GOW(fgetc_unlocked, 
//GO(fgetgrent, 
//GOW(fgetgrent_r, 
//GO(fgetpos, 
//GO(fgetpos64, 
//GO(fgetpwent, 
//GOW(fgetpwent_r, 
//GOW(fgets, 
//GO(__fgets_chk, 
//GO(fgetsgent, 
//GOW(fgetsgent_r, 
//GO(fgetspent, 
//GOW(fgetspent_r, 
//GOW(fgets_unlocked, 
//GO(__fgets_unlocked_chk, 
//GOW(fgetwc, 
//GOW(fgetwc_unlocked, 
//GO(fgetws, 
//GO(__fgetws_chk, 
//GO(fgetws_unlocked, 
//GO(__fgetws_unlocked_chk, 
//GO(fgetxattr, 
GOW(fileno, iFp)
GOW(fileno_unlocked, iFp)
GO(__finite, iFd)
GOW(finite, iFd)
GO(__finitef, iFf)
GOW(finitef, iFf)
//GO(__finitel, 
//GOW(finitel, 
//GO(__flbf, 
//GO(flistxattr, 
//GOW(flock, 
//GOW(flockfile, 
//GOW(_flushlbf, 
//GO(fmemopen, 
//GO(fmemopen, 
//GO(fmtmsg, 
//GO(fnmatch, 
GOM(fopen, pFEpp)
GOM(fopen64, pFEpp)  // Weak
//GO(fopencookie, 
//GO(__fork, 
GOM(fork, lFEv) // Weak
//GO(__fortify_fail, 
//GOW(fpathconf, 
//GO(__fpending, 
GOM(fprintf, iFEppV)
GOM(__fprintf_chk, iFEpvpV)
//DATA(__fpu_control, 
//GO(__fpurge, 
GO(fputc, iFip)
GO(fputc_unlocked, iFip)
GOW(fputs, iFpp)
GOW(fputs_unlocked, iFpp)
GO(fputwc, iFip)
GO(fputwc_unlocked, iFip)
GO(fputws, iFpp)
GO(fputws_unlocked, iFpp)
GOW(fread, LFpLLp)
//GO(__freadable, 
//GO(__fread_chk, 
//GO(__freading, 
GOW(fread_unlocked, LFpLLp)
GO(__fread_unlocked_chk, LFpLLLp)
GO(free, vFp)
//GO(freeaddrinfo, 
//GOW(freeifaddrs, 
//GO(__freelocale, 
//GOW(freelocale, 
//GO(fremovexattr, 
//GO(freopen, 
//GO(freopen64, 
//GOW(frexp, 
//GOW(frexpf, 
//GOW(frexpl, 
//GO(fscanf, 
GO(fseek, iFpli)
GOW(fseeko, iFpli)
GO(__fseeko64, iFpIi)
GOW(fseeko64, iFpIi)
GO(__fsetlocking, iFpi)
GO(fsetpos, iFpp)
GO(fsetpos64, iFpp)
//GO(fsetxattr, 
//GOW(fstatfs, 
//GOW(fstatfs64, 
//GOW(fstatvfs, 
//GOW(fstatvfs64, 
//GO(fsync, 
GOW(ftell, lFp)
GOW(ftello, lFp)
GO(__ftello64, IFp)
GOW(ftello64, IFp)
//GO(ftime, 
//GO(ftok, 
//GOW(ftruncate, 
//GOW(ftruncate64, 
//GOW(ftrylockfile, 
//GOW(fts64_children, 
//GOW(fts64_close, 
//GOW(fts64_open, 
//GOW(fts64_read, 
//GOW(fts64_set, 
//GO(fts_children, 
//GO(fts_close, 
//GO(fts_open, 
//GO(fts_read, 
//GO(fts_set, 
//GO(ftw, 
//GOW(ftw64, 
//GOW(funlockfile, 
//GO(futimens, 
//GOW(futimes, 
//GO(futimesat, 
//GO(fwide, 
//GOW(fwprintf, 
//GO(__fwprintf_chk, 
//GO(__fwritable, 
GOW(fwrite, LFpLLp)
//GO(fwrite_unlocked, 
//GO(__fwriting, 
//GO(fwscanf, 
GO(__fxstat, iFiip)
GO(__fxstat64, iFiip)
GO(__fxstatat, iFiippi)
GO(__fxstatat64, iFiippi)
//GO(__gai_sigqueue, 
//GO(gai_strerror, 
//GO(__gconv_get_alias_db, 
//GO(__gconv_get_cache, 
//GO(__gconv_get_modules_db, 
//GO(__gconv_transliterate, 
//GO(gcvt, 
//GO(getaddrinfo, 
//GO(getaliasbyname, 
//GO(getaliasbyname_r, 
//GO(getaliasent, 
//GO(getaliasent_r, 
//GO(__getauxval, 
//GOW(getauxval, 
//GOW(get_avphys_pages, 
GOW(getc, iFp)
GO(getchar, iFv)
GO(getchar_unlocked, iFv)
GOM(getcontext, iFEp)   //Weak
GOW(getc_unlocked, iFp)
GO(get_current_dir_name, pFv)
GOW(getcwd, pFpL)
GO(__getcwd_chk, pFpLL)
GO(getdate, pFp)
//DATAB(getdate_err, 
//GOW(getdate_r, 
//GOW(__getdelim, 
//GOW(getdelim, 
//GOW(getdirentries, 
//GO(getdirentries64, 
//GO(getdomainname, 
//GO(__getdomainname_chk, 
GOW(getdtablesize, iFv)
GOW(getegid, iFv)
//GO(getentropy, 
GO(getenv, pFp)
GOW(geteuid, pFv)
//GO(getfsent, 
//GO(getfsfile, 
//GO(getfsspec, 
//GOW(getgid, 
//GO(getgrent, 
//GO(getgrent_r, 
//GO(getgrgid, 
//GO(getgrgid_r, 
//GO(getgrnam, 
//GO(getgrnam_r, 
//GO(getgrouplist, 
//GOW(getgroups, 
//GO(__getgroups_chk, 
//GO(gethostbyaddr, 
//GO(gethostbyaddr_r, 
//GO(gethostbyname, 
//GO(gethostbyname2, 
//GO(gethostbyname2_r, 
//GO(gethostbyname_r, 
//GO(gethostent, 
//GO(gethostent_r, 
//GO(gethostid, 
//GOW(gethostname, 
//GO(__gethostname_chk, 
//GOW(getifaddrs, 
//GO(getipv4sourcefilter, 
//GOW(getitimer, 
//GO(get_kernel_syms, 
//GOW(getline, 
//GO(getloadavg, 
//GO(getlogin, 
//GOW(getlogin_r, 
//GO(__getlogin_r_chk, 
//GO(getmntent, 
//GO(__getmntent_r, 
//GOW(getmntent_r, 
//GO(getmsg, 
//GO(get_myaddress, 
//GO(getnameinfo, 
//GO(getnetbyaddr, 
//GO(getnetbyaddr_r, 
//GO(getnetbyname, 
//GO(getnetbyname_r, 
//GO(getnetent, 
//GO(getnetent_r, 
//GO(getnetgrent, 
//GOW(getnetgrent_r, 
//GO(getnetname, 
//GOW(get_nprocs, 
//GOW(get_nprocs_conf, 
//GO(getopt, 
//GO(getopt_long, 
//GO(getopt_long_only, 
GO(__getpagesize, iFv)
GOW(getpagesize, iFv)
//GO(getpass, 
//GOW(getpeername, 
//GO(__getpgid, 
//GOW(getpgid, 
//GO(getpgrp, 
//GOW(get_phys_pages, 
GO(__getpid, uFv)
GO(getpid, uFv)
//GO(getpmsg, 
//GOW(getppid, 
GOW(getpriority, iFii)
//GO(getprotobyname, 
//GO(getprotobyname_r, 
//GO(getprotobynumber, 
//GO(getprotobynumber_r, 
//GO(getprotoent, 
//GO(getprotoent_r, 
//GOW(getpt, 
//GO(getpublickey, 
//GOW(getpw, 
//GO(getpwent, 
//GO(getpwent_r, 
//GO(getpwnam, 
//GO(getpwnam_r, 
//GO(getpwuid, 
//GO(getpwuid_r, 
//GO(getrandom, 
//GO(getresgid, 
//GO(getresuid, 
GO(__getrlimit, iFip)
GOW(getrlimit, iFip)
GOW(getrlimit64, iFip)
//GO(getrpcbyname, 
//GO(getrpcbyname_r, 
//GO(getrpcbynumber, 
//GO(getrpcbynumber_r, 
//GO(getrpcent, 
//GO(getrpcent_r, 
//GO(getrpcport, 
//GOW(getrusage, 
//GOW(gets, 
//GO(__gets_chk, 
//GO(getsecretkey, 
//GO(getservbyname, 
//GO(getservbyname_r, 
//GO(getservbyport, 
//GO(getservbyport_r, 
//GO(getservent, 
//GO(getservent_r, 
//GO(getsgent, 
//GO(getsgent_r, 
//GO(getsgnam, 
//GO(getsgnam_r, 
//GO(getsid, 
//GOW(getsockname, 
//GOW(getsockopt, 
//GO(getsourcefilter, 
//GO(getspent, 
//GO(getspent_r, 
//GO(getspnam, 
//GO(getspnam_r, 
//GO(getsubopt, 
//GOW(gettext, 
//GOI(__gettimeofday, 
//GOI(gettimeofday, 
//GOW(getttyent, 
//GOW(getttynam, 
//GOW(getuid, 
//GO(getusershell, 
//GOW(getutent, 
//GOW(getutent_r, 
//GOW(getutid, 
//GOW(getutid_r, 
//GOW(getutline, 
//GOW(getutline_r, 
//GO(getutmp, 
//GO(getutmpx, 
//GO(getutxent, 
//GO(getutxid, 
//GO(getutxline, 
//GO(getw, 
//GOW(getwc, 
//GO(getwchar, 
//GO(getwchar_unlocked, 
//GOW(getwc_unlocked, 
//GO(getwd, 
//GO(__getwd_chk, 
//GO(getxattr, 
//GO(glob, 
//GO(glob, 
//GO(glob64, 
//GO(glob64, 
//GO(globfree, 
//GOW(globfree64, 
//GOW(glob_pattern_p, 
//GO(gmtime, 
//GO(__gmtime_r, 
//GOW(gmtime_r, 
//GOW(gnu_dev_major, 
//GOW(gnu_dev_makedev, 
//GOW(gnu_dev_minor, 
//GOW(gnu_get_libc_release, 
//GOW(gnu_get_libc_version, 
//GO(grantpt, 
//GOW(group_member, 
//GOW(gsignal, 
//GO(gtty, 
//GOW(hasmntopt, 
//GO(hcreate, 
//GOW(hcreate_r, 
//GOW(hdestroy, 
//GOW(hdestroy_r, 
//DATA(h_errlist, 
//DATAB(__h_errno, 
//GO(__h_errno_location, 
//GO(herror, 
//GO(host2netname, 
//GO(hsearch, 
//GOW(hsearch_r, 
//GO(hstrerror, 
//GO(htonl, 
//GO(htons, 
//GO(iconv, 
//GO(iconv_close, 
//GO(iconv_open, 
//GO(__idna_from_dns_encoding, 
//GO(__idna_to_dns_encoding, 
//GOW(if_freenameindex, 
//GOW(if_indextoname, 
//GOW(if_nameindex, 
//GOW(if_nametoindex, 
//GOW(imaxabs, 
//GOW(imaxdiv, 
//GOI(index, 
//GO(inet6_opt_append, 
//GO(inet6_opt_find, 
//GO(inet6_opt_finish, 
//GO(inet6_opt_get_val, 
//GO(inet6_opt_init, 
//GO(inet6_option_alloc, 
//GO(inet6_option_append, 
//GO(inet6_option_find, 
//GO(inet6_option_init, 
//GO(inet6_option_next, 
//GO(inet6_option_space, 
//GO(inet6_opt_next, 
//GO(inet6_opt_set_val, 
//GO(inet6_rth_add, 
//GO(inet6_rth_getaddr, 
//GO(inet6_rth_init, 
//GO(inet6_rth_reverse, 
//GO(inet6_rth_segments, 
//GO(inet6_rth_space, 
//GO(__inet6_scopeid_pton, 
//GOW(inet_addr, 
//GOW(inet_aton, 
//GO(__inet_aton_exact, 
//GO(inet_lnaof, 
//GOW(inet_makeaddr, 
//GO(inet_netof, 
//GO(inet_network, 
//GO(inet_nsap_addr, 
//GO(inet_nsap_ntoa, 
//GO(inet_ntoa, 
//GO(inet_ntop, 
//GOW(inet_pton, 
//GO(__inet_pton_length, 
//GO(initgroups, 
//GO(init_module, 
//GOW(initstate, 
//GOW(initstate_r, 
//GO(innetgr, 
//GO(inotify_add_watch, 
//GO(inotify_init, 
//GO(inotify_init1, 
//GO(inotify_rm_watch, 
//GO(insque, 
//GO(__internal_endnetgrent, 
//GO(__internal_getnetgrent_r, 
//GO(__internal_setnetgrent, 
//DATA(_IO_2_1_stderr_, 
//DATA(_IO_2_1_stdin_, 
//DATA(_IO_2_1_stdout_, 
//GO(_IO_adjust_column, 
//GO(_IO_adjust_wcolumn, 
GOW(ioctl, iFiLN)
//GO(_IO_default_doallocate, 
//GO(_IO_default_finish, 
//GO(_IO_default_pbackfail, 
//GO(_IO_default_uflow, 
//GO(_IO_default_xsgetn, 
//GO(_IO_default_xsputn, 
//GO(_IO_doallocbuf, 
//GO(_IO_do_write, 
//GO(_IO_enable_locks, 
//GO(_IO_fclose, 
//GO(_IO_fdopen, 
//GO(_IO_feof, 
//GO(_IO_ferror, 
//GO(_IO_fflush, 
//GO(_IO_fgetpos, 
//GO(_IO_fgetpos64, 
//GO(_IO_fgets, 
//GO(_IO_file_attach, 
//GO(_IO_file_close, 
//GO(_IO_file_close_it, 
//GO(_IO_file_doallocate, 
//GO(_IO_file_finish, 
//GO(_IO_file_fopen, 
//GO(_IO_file_init, 
//DATA(_IO_file_jumps, 
//GO(_IO_file_open, 
//GO(_IO_file_overflow, 
//GO(_IO_file_read, 
//GO(_IO_file_seek, 
//GO(_IO_file_seekoff, 
//GO(_IO_file_setbuf, 
//GO(_IO_file_stat, 
//GO(_IO_file_sync, 
//GO(_IO_file_underflow, 
//GO(_IO_file_write, 
//GO(_IO_file_xsputn, 
//GO(_IO_flockfile, 
//GO(_IO_flush_all, 
//GO(_IO_flush_all_linebuffered, 
//GO(_IO_fopen, 
//GOW(_IO_fprintf, 
//GO(_IO_fputs, 
//GO(_IO_fread, 
//GO(_IO_free_backup_area, 
//GO(_IO_free_wbackup_area, 
//GO(_IO_fsetpos, 
//GO(_IO_fsetpos64, 
//GO(_IO_ftell, 
//GO(_IO_ftrylockfile, 
//GO(_IO_funlockfile, 
//GO(_IO_fwrite, 
//GO(_IO_getc, 
//GO(_IO_getline, 
//GO(_IO_getline_info, 
//GO(_IO_gets, 
//GO(_IO_init, 
//GO(_IO_init_marker, 
//GO(_IO_init_wmarker, 
//GO(_IO_iter_begin, 
//GO(_IO_iter_end, 
//GO(_IO_iter_file, 
//GO(_IO_iter_next, 
//GO(_IO_least_wmarker, 
//GO(_IO_link_in, 
//DATA(_IO_list_all, 
//GO(_IO_list_lock, 
//GO(_IO_list_resetlock, 
//GO(_IO_list_unlock, 
//GO(_IO_marker_delta, 
//GO(_IO_marker_difference, 
//GO(_IO_padn, 
//GO(_IO_peekc_locked, 
//GO(ioperm, 
//GO(iopl, 
//GO(_IO_popen, 
//GO(_IO_printf, 
//GO(_IO_proc_close, 
//GO(_IO_proc_open, 
//GO(_IO_putc, 
//GO(_IO_puts, 
//GO(_IO_remove_marker, 
//GO(_IO_seekmark, 
//GO(_IO_seekoff, 
//GO(_IO_seekpos, 
//GO(_IO_seekwmark, 
//GO(_IO_setb, 
//GO(_IO_setbuffer, 
//GO(_IO_setvbuf, 
//GO(_IO_sgetn, 
//GO(_IO_sprintf, 
//GO(_IO_sputbackc, 
//GO(_IO_sputbackwc, 
//GO(_IO_sscanf, 
//GO(_IO_str_init_readonly, 
//GO(_IO_str_init_static, 
//GO(_IO_str_overflow, 
//GO(_IO_str_pbackfail, 
//GO(_IO_str_seekoff, 
//GO(_IO_str_underflow, 
//GO(_IO_sungetc, 
//GO(_IO_sungetwc, 
//GO(_IO_switch_to_get_mode, 
//GO(_IO_switch_to_main_wget_area, 
//GO(_IO_switch_to_wbackup_area, 
//GO(_IO_switch_to_wget_mode, 
//GO(_IO_ungetc, 
//GO(_IO_un_link, 
//GO(_IO_unsave_markers, 
//GO(_IO_unsave_wmarkers, 
//GO(_IO_vfprintf, 
//GO(_IO_vfscanf, 
//GO(_IO_vsprintf, 
//GO(_IO_wdefault_doallocate, 
//GO(_IO_wdefault_finish, 
//GO(_IO_wdefault_pbackfail, 
//GO(_IO_wdefault_uflow, 
//GO(_IO_wdefault_xsgetn, 
//GO(_IO_wdefault_xsputn, 
//GO(_IO_wdoallocbuf, 
//GO(_IO_wdo_write, 
//DATA(_IO_wfile_jumps, 
//GO(_IO_wfile_overflow, 
//GO(_IO_wfile_seekoff, 
//GO(_IO_wfile_sync, 
//GO(_IO_wfile_underflow, 
//GO(_IO_wfile_xsputn, 
//GO(_IO_wmarker_delta, 
//GO(_IO_wsetb, 
//GO(iruserok, 
//GO(iruserok_af, 
GO(isalnum, iFi)
//GO(__isalnum_l, 
//GOW(isalnum_l, 
GO(isalpha, iFi)
//GO(__isalpha_l, 
GOW(isalpha_l, iFip)
GO(isascii, iFi)
//GOW(__isascii_l, 
//GO(isastream, 
GOW(isatty, iFi)
GO(isblank, iFi)
//GO(__isblank_l, 
//GOW(isblank_l, 
GO(iscntrl, iFi)
//GO(__iscntrl_l, 
//GOW(iscntrl_l, 
//GO(__isctype, 
//GOW(isctype, 
GO(isdigit, iFi)
//GO(__isdigit_l, 
//GOW(isdigit_l, 
//GO(isfdtype, 
GO(isgraph, iFi)
//GO(__isgraph_l, 
//GOW(isgraph_l, 
GO(__isinf, iFd)
GOW(isinf, iFd)
GO(__isinff, iFf)
GOW(isinff, iFf)
//GO(__isinfl, 
//GOW(isinfl, 
GO(islower, iFi)
//GO(__islower_l, 
//GOW(islower_l, 
GO(__isnan, iFd)
GOW(isnan, iFd)
GO(__isnanf, iFf)
GOW(isnanf, iFf)
//GO(__isnanl, 
//GOW(isnanl, 
//GO(__isoc99_fscanf, 
//GO(__isoc99_fwscanf, 
//GO(__isoc99_scanf, 
//GO(__isoc99_sscanf, 
//GO(__isoc99_swscanf, 
//GO(__isoc99_vfscanf, 
//GO(__isoc99_vfwscanf, 
//GO(__isoc99_vscanf, 
//GO(__isoc99_vsscanf, 
//GO(__isoc99_vswscanf, 
//GO(__isoc99_vwscanf, 
//GO(__isoc99_wscanf, 
GO(isprint, iFi)
//GO(__isprint_l, 
//GOW(isprint_l, 
GO(ispunct, iFi)
//GO(__ispunct_l, 
//GOW(ispunct_l, 
GO(isspace, iFi)
//GO(__isspace_l, 
//GOW(isspace_l, 
GO(isupper, iFi)
//GO(__isupper_l, 
//GOW(isupper_l, 
GOW(iswalnum, iFi)
//GO(__iswalnum_l, 
GOW(iswalnum_l, iFip)
GOW(iswalpha, iFi)
//GO(__iswalpha_l, 
GOW(iswalpha_l, iFip)
GOW(iswblank, iFi)
//GO(__iswblank_l, 
GOW(iswblank_l, iFip)
GOW(iswcntrl, iFi)
//GO(__iswcntrl_l, 
GOW(iswcntrl_l, iFip)
//GO(__iswctype, 
//GOW(iswctype, 
//GO(__iswctype_l, 
//GOW(iswctype_l, 
GOW(iswdigit, iFi)
//GO(__iswdigit_l, 
GOW(iswdigit_l, iFip)
GOW(iswgraph, iFi)
//GO(__iswgraph_l, 
GOW(iswgraph_l, iFip)
GOW(iswlower, iFi)
//GO(__iswlower_l, 
GOW(iswlower_l, iFip)
GOW(iswprint, iFi)
//GO(__iswprint_l, 
GOW(iswprint_l, iFip)
GOW(iswpunct, iFi)
//GO(__iswpunct_l, 
GOW(iswpunct_l, iFip)
GOW(iswspace, iFi)
//GO(__iswspace_l, 
GOW(iswspace_l, iFip)
GOW(iswupper, iFi)
//GO(__iswupper_l, 
GOW(iswupper_l, iFip)
GOW(iswxdigit, iFi)
//GO(__iswxdigit_l, 
GOW(iswxdigit_l, iFip)
GO(isxdigit, iFi)
//GO(__isxdigit_l, 
GOW(isxdigit_l, iFip)
//GO(__ivaliduser, 
GO(jrand48, iFp)
//GOW(jrand48_r, 
//GO(key_decryptsession, 
//GO(key_decryptsession_pk, 
//DATAB(__key_decryptsession_pk_LOCAL, 
//GO(key_encryptsession, 
//GO(key_encryptsession_pk, 
//DATAB(__key_encryptsession_pk_LOCAL, 
//GO(key_gendes, 
//DATAB(__key_gendes_LOCAL, 
//GO(key_get_conv, 
//GO(key_secretkey_is_set, 
//GO(key_setnet, 
//GO(key_setsecret, 
GOW(kill, iFli)
GO(killpg, iFii)
//GO(klogctl, 
//GO(l64a, 
//GO(labs, 
//GO(lchmod, 
//GOW(lchown, 
//GOW(lckpwdf, 
//GO(lcong48, 
//GOW(lcong48_r, 
//GOW(ldexp, 
//GOW(ldexpf, 
//GOW(ldexpl, 
//GO(ldiv, 
//GO(lfind, 
//GO(lgetxattr, 
//GO(__libc_alloca_cutoff, 
//GO(__libc_allocate_once_slow, 
//GO(__libc_allocate_rtsig, 
//GO(__libc_allocate_rtsig_private, 
//GO(__libc_alloc_buffer_alloc_array, 
//GO(__libc_alloc_buffer_allocate, 
//GO(__libc_alloc_buffer_copy_bytes, 
//GO(__libc_alloc_buffer_copy_string, 
//GO(__libc_alloc_buffer_create_failure, 
//GO(__libc_calloc, 
//GO(__libc_clntudp_bufcreate, 
//GO(__libc_current_sigrtmax, 
//GO(__libc_current_sigrtmax_private, 
//GO(__libc_current_sigrtmin, 
//GO(__libc_current_sigrtmin_private, 
//GO(__libc_dlclose, 
//GO(__libc_dlopen_mode, 
//GO(__libc_dlsym, 
//GO(__libc_dlvsym, 
//GO(__libc_dynarray_at_failure, 
//GO(__libc_dynarray_emplace_enlarge, 
//GO(__libc_dynarray_finalize, 
//GO(__libc_dynarray_resize, 
//GO(__libc_dynarray_resize_clear, 
//GO(__libc_fatal, 
//GO(__libc_fcntl64, 
//GO(__libc_fork, 
//GO(__libc_free, 
//GO(__libc_freeres, 
//GO(__libc_ifunc_impl_list, 
//GO(__libc_init_first, 
//GO(__libc_longjmp, 
//GO(__libc_mallinfo, 
//GO(__libc_malloc, 
//GO(__libc_mallopt, 
//GO(__libc_memalign, 
//GO(__libc_msgrcv, 
//GO(__libc_msgsnd, 
//GO(__libc_pread, 
//GO(__libc_pthread_init, 
//GO(__libc_pvalloc, 
//GO(__libc_pwrite, 
//GO(__libc_readline_unlocked, 
//GO(__libc_realloc, 
//GO(__libc_reallocarray, 
//GO(__libc_rpc_getport, 
//GO(__libc_sa_len, 
//GO(__libc_scratch_buffer_grow, 
//GO(__libc_scratch_buffer_grow_preserve, 
//GO(__libc_scratch_buffer_set_array_size, 
//GOW(__libc_secure_getenv, 
//GO(__libc_siglongjmp, 
GOM(__libc_start_main, iFEpippppp)
//GO(__libc_system, 
//GO(__libc_thread_freeres, 
//GO(__libc_valloc, 
//GO(__libc_vfork, 
//GOW(link, 
//GO(linkat, 
//GOW(listen, 
//GO(listxattr, 
//GO(llabs, 
//GO(lldiv, 
//GO(llistxattr, 
//GO(llseek, 
//DATAB(loc1, 
//DATAB(loc2, 
//GO(localeconv, 
//GO(localtime, 
//GOW(localtime_r, 
//GO(lockf, 
//GOW(lockf64, 
//DATAB(locs, 
//GOW(_longjmp, 
//GOW(longjmp, 
//GO(__longjmp_chk, 
//GO(lrand48, 
//GO(lrand48_r, 
//GO(lremovexattr, 
//GO(lsearch, 
GO(__lseek, IFiIi)
GOW(lseek, IFiIi)
GOW(lseek64, IFiIi)
//GO(lsetxattr, 
//GO(lutimes, 
//GO(__lxstat, iFipp)
//GO(__lxstat64, iFipp)
//GO(__madvise, 
//GOW(madvise, 
GOM(makecontext, iFEppiV)   //weak
//GOW(mallinfo, 
GO(malloc, pFL) // need to wrap to clear allocated memory?
//GO(malloc_get_state, 
//GOW(malloc_info, 
//GO(malloc_set_state, 
//GOW(malloc_stats, 
//GOW(malloc_trim, 
//GOW(malloc_usable_size, 
//GOW(mallopt, 
//DATAB(mallwatch, 
//GO(mblen, 
//GO(__mbrlen, 
//GOW(mbrlen, 
//GO(mbrtoc16, 
//GOW(mbrtoc32, 
//GO(__mbrtowc, 
//GOW(mbrtowc, 
//GOW(mbsinit, 
//GOW(mbsnrtowcs, 
//GO(__mbsnrtowcs_chk, 
//GOW(mbsrtowcs, 
//GO(__mbsrtowcs_chk, 
//GO(mbstowcs, 
//GO(__mbstowcs_chk, 
//GO(mbtowc, 
//GO(mcheck, 
//GO(mcheck_check_all, 
//GO(mcheck_pedantic, 
//GO(_mcleanup, 
//GO(_mcount, 
//GOW(mcount, 
//GOW(memalign, 
GOW(memccpy, pFppiL)
GO(memchr, pFpiL)
GO(memcmp, iFppL)
GO(memcpy, pFppL)
GO(__memcpy_chk, pFppuL)
//GO(memfd_create, 
//GO(memfrob, 
//GOW(memmem, 
GO(memmove, pFppL)
GO(__memmove_chk, pFppLL)
//GOI(__mempcpy, 
//GOI(mempcpy, 
//GOI(__mempcpy_chk, 
GOW(memrchr, pFpiu)
GO(memset, pFpiL)
GO(__memset_chk, pFpiuu)
//GO(__mempcpy_small, 
//GO(__merge_grp, 
//GO(mincore, 
GOW(mkdir, iFpu)
GO(mkdirat, iFipu)
GO(mkdtemp, pFp)
GO(mkfifo, iFpu)
GO(mkfifoat, iFipu)
//GO(mkostemp, 
//GOW(mkostemp64, 
//GO(mkostemps, 
//GOW(mkostemps64, 
//GO(mkstemp, 
//GOW(mkstemp64, 
//GO(mkstemps, 
//GOW(mkstemps64, 
//GO(__mktemp, 
//GOW(mktemp, 
//GO(mktime, 
//GO(mlock, 
//GO(mlock2, 
//GO(mlockall, 
//GO(__mmap, 
//GOW(mmap, 
//GOW(mmap64, 
//GOW(modf, 
//GOW(modff, 
//GOW(modfl, 
//GOW(modify_ldt, 
//GOW(moncontrol, 
//GO(__monstartup, 
//GOW(monstartup, 
//DATA(__morecore, 
//GOW(mount, 
//GO(mprobe, 
//GO(__mprotect, 
//GOW(mprotect, 
//GO(mrand48, 
//GO(mrand48_r, 
//GOW(mremap, 
//GO(msgctl, 
//GO(msgget, 
//GOW(msgrcv, 
//GOW(msgsnd, 
//GO(msync, 
//GO(mtrace, 
//GO(munlock, 
//GO(munlockall, 
//GO(__munmap, 
//GOW(munmap, 
//GO(muntrace, 
GO(name_to_handle_at, iFipppi)
//GO(__nanosleep, 
//GOW(nanosleep, 
//GO(__nanosleep_nocancel, 
//GO(__netlink_assert_response, 
//GO(netname2host, 
//GO(netname2user, 
GO(__newlocale, pFipp)
GOW(newlocale, pFipp)
//GO(nfsservctl, 
//GO(nftw, 
//GO(nftw, 
//GO(nftw64, 
//GO(nftw64, 
//GOW(ngettext, 
//GO(nice, 
//DATAB(_nl_domain_bindings, 
GO(nl_langinfo, pFu)
GO(__nl_langinfo_l, pFup)
GOW(nl_langinfo_l, pFup)
//DATAB(_nl_msg_cat_cntr, 
//GO(nrand48, 
//GOW(nrand48_r, 
//GO(__nss_configure_lookup, 
//GO(__nss_database_lookup, 
//GO(__nss_disable_nscd, 
//GO(_nss_files_parse_grent, 
//GO(_nss_files_parse_pwent, 
//GO(_nss_files_parse_sgent, 
//GO(_nss_files_parse_spent, 
//GO(__nss_group_lookup, 
//GO(__nss_group_lookup2, 
//GO(__nss_hash, 
//GO(__nss_hostname_digits_dots, 
//GO(__nss_hosts_lookup, 
//GO(__nss_hosts_lookup2, 
//GO(__nss_lookup, 
//GO(__nss_lookup_function, 
//GO(__nss_next, 
//GO(__nss_next2, 
//GO(__nss_passwd_lookup, 
//GO(__nss_passwd_lookup2, 
//GO(__nss_services_lookup2, 
//GOW(ntohl, 
//GOW(ntohs, 
//GOW(ntp_adjtime, 
//GO(ntp_gettime, 
//GO(ntp_gettimex, 
//DATAB(_null_auth, 
//DATAB(_obstack, 
//GO(_obstack_allocated_p, 
//DATA(obstack_alloc_failed_handler, 
//GO(_obstack_begin, 
//GO(_obstack_begin_1, 
//DATA(obstack_exit_failure, 
//GO(_obstack_free, 
//GO(obstack_free, 
//GO(_obstack_memory_used, 
//GO(_obstack_newchunk, 
//GOW(obstack_printf, 
//GO(__obstack_printf_chk, 
//GOW(obstack_vprintf, 
//GO(__obstack_vprintf_chk, 
//GOW(on_exit, 
GOM(__open, iFEpOu) //Weak
GOM(open, iFEpOu)    //Weak
GO(__open_2, iFpO)
//GOW(__open64, 
GOM(open64, iFEpOu) //Weak
//GO(__open64_2, 
//GO(__open64_nocancel, 
//GOW(openat, 
//GO(__openat_2, 
//GOW(openat64, 
//GO(__openat64_2, 
//GO(open_by_handle_at, 
//GO(__open_catalog, 
GOW(opendir, pFp)
GO(openlog, vFpii)
//GOW(open_memstream, 
//GO(__open_nocancel, 
//GO(open_wmemstream, 
//DATAB(optarg, 
//DATA(opterr, 
//DATA(optind, 
//DATA(optopt, 
//GO(__overflow, 
//GO(parse_printf_format, 
//GO(passwd2des, 
//GOW(pathconf, 
//GOW(pause, 
//GO(__pause_nocancel, 
//GO(pclose, 
//GO(perror, 
//GOW(personality, 
//GO(__pipe, 
//GOW(pipe, 
//GOW(pipe2, 
//GO(pivot_root, 
//GO(pkey_alloc, 
//GO(pkey_free, 
//GO(pkey_get, 
//GO(pkey_mprotect, 
//GO(pkey_set, 
//GO(pmap_getmaps, 
//GO(pmap_getport, 
//GO(pmap_rmtcall, 
//GO(pmap_set, 
//GO(pmap_unset, 
//GO(__poll, 
//GOW(poll, 
//GO(__poll_chk, 
//GO(popen, 
//GO(posix_fadvise, 
//GOW(posix_fadvise64, 
//GO(posix_fallocate, 
//GO(posix_fallocate64, 
//GO(__posix_getopt, 
//GO(posix_madvise, 
//GOW(posix_memalign, 
//GOW(posix_openpt, 
//GO(posix_spawn, 
//GO(posix_spawn, 
//GO(posix_spawnattr_destroy, 
//GO(posix_spawnattr_getflags, 
//GO(posix_spawnattr_getpgroup, 
//GO(posix_spawnattr_getschedparam, 
//GO(posix_spawnattr_getschedpolicy, 
//GO(posix_spawnattr_getsigdefault, 
//GO(posix_spawnattr_getsigmask, 
//GO(posix_spawnattr_init, 
//GO(posix_spawnattr_setflags, 
//GO(posix_spawnattr_setpgroup, 
//GO(posix_spawnattr_setschedparam, 
//GO(posix_spawnattr_setschedpolicy, 
//GO(posix_spawnattr_setsigdefault, 
//GO(posix_spawnattr_setsigmask, 
//GO(posix_spawn_file_actions_addclose, 
//GO(posix_spawn_file_actions_adddup2, 
//GO(posix_spawn_file_actions_addopen, 
//GO(posix_spawn_file_actions_destroy, 
//GO(posix_spawn_file_actions_init, 
//GO(posix_spawnp, 
//GO(posix_spawnp, 
//GO(ppoll, 
//GO(__ppoll_chk, 
//GOW(prctl, 
GOW(pread, lFipLl)
GOW(__pread64, lFipLI)
GOW(pread64, lFipLI)
//GO(__pread64_chk, 
//GO(__pread_chk, 
//GO(preadv, 
//GO(preadv2, 
//GO(preadv64, 
//GO(preadv64v2, 
GOM(printf, iFEpV)
//GO(__printf_chk, 
//GO(__printf_fp, 
//GO(printf_size, 
//GO(printf_size_info, 
//GO(prlimit, 
//GOW(prlimit64, 
//GO(process_vm_readv, 
//GO(process_vm_writev, 
//GOW(profil, 
//GO(__profile_frequency, 
//DATA(__progname, 
//DATA(__progname_full, 
//GOW(pselect, 
//GO(psiginfo, 
//GO(psignal, 
//GO(pthread_attr_destroy, 
//GO(pthread_attr_getdetachstate, 
//GO(pthread_attr_getinheritsched, 
//GO(pthread_attr_getschedparam, 
//GO(pthread_attr_getschedpolicy, 
//GO(pthread_attr_getscope, 
//GO(pthread_attr_init, 
//GO(pthread_attr_setdetachstate, 
//GO(pthread_attr_setinheritsched, 
//GO(pthread_attr_setschedparam, 
//GO(pthread_attr_setschedpolicy, 
//GO(pthread_attr_setscope, 
//GO(pthread_condattr_destroy, 
//GO(pthread_condattr_init, 
//GO(pthread_cond_broadcast, 
//GO(pthread_cond_broadcast, 
//GO(pthread_cond_destroy, 
//GO(pthread_cond_destroy, 
//GO(pthread_cond_init, 
//GO(pthread_cond_init, 
//GO(pthread_cond_signal, 
//GO(pthread_cond_signal, 
//GO(pthread_cond_timedwait, 
//GO(pthread_cond_timedwait, 
//GO(pthread_cond_wait, 
//GO(pthread_cond_wait, 
//GO(pthread_equal, 
//GO(pthread_exit, 
//GO(pthread_getschedparam, 
//GO(pthread_mutex_destroy, 
//GO(pthread_mutex_init, 
//GO(pthread_mutex_lock, 
//GO(pthread_mutex_unlock, 
//GO(pthread_self, 
//GO(pthread_setcancelstate, 
//GO(pthread_setcanceltype, 
//GO(pthread_setschedparam, 
//GO(ptrace, 
//GO(ptsname, 
//GOW(ptsname_r, 
//GO(__ptsname_r_chk, 
GOW(putc, iFip)
GO(putchar, iFi)
GO(putchar_unlocked, iFi)
GO(putc_unlocked, iFip)
GO(putenv, iFp)
//GO(putgrent, 
//GO(putmsg, 
//GO(putpmsg, 
//GO(putpwent, 
GOW(puts, iFp)
//GO(putsgent, 
//GO(putspent, 
GOW(pututline, pFp)
//GO(pututxline, 
//GO(putw, 
GO(putwc, iFip)
//GO(putwchar, 
GO(putwchar_unlocked, iFi)
GO(putwc_unlocked, iFip)
//GOW(pvalloc, 
//GOW(pwrite, 
//GOW(__pwrite64, 
GOW(pwrite64, lFipLI)
//GO(pwritev, 
//GO(pwritev2, 
GO(pwritev64, lFipiI)
//GO(pwritev64v2, 
//GO(qecvt, 
//GOW(qecvt_r, 
//GO(qfcvt, 
//GOW(qfcvt_r, 
//GO(qgcvt, 
//GO(qsort, 
//GOW(qsort_r, 
//GO(query_module, 
//GO(quick_exit, 
//GO(quick_exit, 
//GO(quotactl, 
//GO(raise, 
GO(rand, iFv)
//GOW(random, 
//GOW(random_r, 
GO(rand_r, iFp)
//GOI(__rawmemchr, 
//GOI(rawmemchr, 
//GO(rcmd, 
//GO(rcmd_af, 
//DATAB(__rcmd_errstr, 
GOW(__read, lFipL)
GO(read, lFipL)
//GOW(readahead, 
//GO(__read_chk, 
GOW(readdir, pFp) // struct direct is 280 byts on x86_64 and ARM64
GOW(readdir64, pFp)
GOW(readdir64_r, iFppp)
GOW(readdir_r, iFppp)
GOW(readlink, pFEppL)
GO(readlinkat, pFippL)
//GO(__readlinkat_chk, 
//GO(__readlink_chk, 
//GO(__read_nocancel, 
GOW(readv, lFipi)
GO(realloc, pFpL)
//GOW(reallocarray, 
GOM(realpath, pFEpp)
//GO(realpath, 
GO2(__realpath_chk, pFppv, my_realpath)
//GO(reboot, 
//GOW(re_comp, 
//GOW(re_compile_fastmap, 
//GOW(re_compile_pattern, 
//GOW(__recv, 
//GOW(recv, 
//GO(__recv_chk, 
//GOW(recvfrom, 
//GO(__recvfrom_chk, 
//GO(recvmmsg, 
//GOW(recvmsg, 
//GOW(re_exec, 
//GOW(regcomp, 
//GOW(regerror, 
//GO(regexec, 
//GO(regexec, 
//GOW(regfree, 
//GO(__register_atfork, 
//GOW(register_printf_function, 
//GOW(register_printf_modifier, 
//GOW(register_printf_specifier, 
//GOW(register_printf_type, 
//GO(registerrpc, 
//GOW(remap_file_pages, 
//GOW(re_match, 
//GOW(re_match_2, 
//DATA(re_max_failures, 
//GO(remove, 
//GO(removexattr, 
//GO(remque, 
//GO(rename, 
//GOW(renameat, 
//GOW(renameat2, 
//DATAB(_res, 
//GOW(re_search, 
//GOW(re_search_2, 
//GOW(re_set_registers, 
//GOW(re_set_syntax, 
//DATAB(_res_hconf, 
//GO(__res_iclose, 
//GO(__res_init, 
//GO(__res_nclose, 
//GO(__res_ninit, 
//GO(__resolv_context_get, 
//GO(__resolv_context_get_override, 
//GO(__resolv_context_get_preinit, 
//GO(__resolv_context_put, 
//DATA(__resp, 
//GO(__res_randomid, 
//GO(__res_state, 
//DATAB(re_syntax_options, 
//GOW(revoke, 
//GO(rewind, 
//GOW(rewinddir, 
//GO(rexec, 
//GO(rexec_af, 
//DATAB(rexecoptions, 
//GOI(rindex, 
//GOW(rmdir, 
//DATAB(rpc_createerr, 
//GO(_rpc_dtablesize, 
//GO(__rpc_thread_createerr, 
//GO(__rpc_thread_svc_fdset, 
//GO(__rpc_thread_svc_max_pollfd, 
//GO(__rpc_thread_svc_pollfd, 
//GO(rpmatch, 
//GO(rresvport, 
//GO(rresvport_af, 
//GO(rtime, 
//GO(ruserok, 
//GO(ruserok_af, 
//GO(ruserpass, 
//GO(__sbrk, 
//GOW(sbrk, 
//GOW(scalbn, 
//GOW(scalbnf, 
//GOW(scalbnl, 
//GOW(scandir, 
//GOW(scandir64, 
//GOW(scandirat, 
//GO(scandirat64, 
//GO(scanf, 
//GO(__sched_cpualloc, 
//GOI(__sched_cpucount, 
//GO(__sched_cpufree, 
//GO(sched_getaffinity, 
//GO(sched_getaffinity, 
//GO(sched_getcpu, 
//GO(__sched_getparam, 
//GOW(sched_getparam, 
//GO(__sched_get_priority_max, 
//GOW(sched_get_priority_max, 
//GO(__sched_get_priority_min, 
//GOW(sched_get_priority_min, 
//GO(__sched_getscheduler, 
//GOW(sched_getscheduler, 
//GOW(sched_rr_get_interval, 
//GO(sched_setaffinity, 
//GO(sched_setaffinity, 
//GOW(sched_setparam, 
//GO(__sched_setscheduler, 
//GOW(sched_setscheduler, 
//GO(__sched_yield, 
//GOW(sched_yield, 
//GOW(__secure_getenv, 
//GOW(secure_getenv, 
//GO(seed48, 
//GOW(seed48_r, 
//GO(seekdir, 
//GO(__select, 
//GOW(select, 
//GO(semctl, 
//GO(semget, 
//GO(semop, 
//GO(semtimedop, 
//GO(__send, 
//GOW(send, 
//GO(sendfile, 
//GOW(sendfile64, 
//GO(__sendmmsg, 
//GOW(sendmmsg, 
//GOW(sendmsg, 
//GOW(sendto, 
//GO(setaliasent, 
//GO(setbuf, 
//GOW(setbuffer, 
//GOW(setcontext, 
//GO(setdomainname, 
//GO(setegid, 
GOW(setenv, iFppi)
//GO(_seterr_reply, 
//GO(seteuid, 
//GO(setfsent, 
//GO(setfsgid, 
//GO(setfsuid, 
//GOW(setgid, 
//GO(setgrent, 
//GO(setgroups, 
//GO(sethostent, 
//GO(sethostid, 
//GO(sethostname, 
//GO(setipv4sourcefilter, 
//GOW(setitimer, 
GOM(_setjmp, iFEp)
GOM(setjmp, iFEp)
GO(setlinebuf, vFp)
GO(setlocale, pFip)
//GO(setlogin, 
//GO(setlogmask, 
//GO(__setmntent, 
//GOW(setmntent, 
//GO(setnetent, 
//GO(setnetgrent, 
//GO(setns, 
//GO(__setpgid, 
//GOW(setpgid, 
//GO(setpgrp, 
GOW(setpriority, iFiii)
//GO(setprotoent, 
//GO(setpwent, 
//GOW(setregid, 
//GOW(setresgid, 
//GOW(setresuid, 
//GOW(setreuid, 
//GOW(setrlimit, 
//GOW(setrlimit64, 
//GO(setrpcent, 
//GO(setservent, 
//GO(setsgent, 
//GOW(setsid, 
//GOW(setsockopt, 
//GO(setsourcefilter, 
//GO(setspent, 
//GOW(setstate, 
//GOW(setstate_r, 
//GOW(settimeofday, 
//GOW(setttyent, 
//GOW(setuid, 
//GO(setusershell, 
//GOW(setutent, 
//GO(setutxent, 
//GOW(setvbuf, 
//GO(setxattr, 
//GO(sgetsgent, 
//GOW(sgetsgent_r, 
//GO(sgetspent, 
//GOW(sgetspent_r, 
//GO(shmat, 
//GO(shmctl, 
//GO(shmdt, 
//GO(shmget, 
//GOW(shutdown, 
GOM(__sigaction, iFEipp)  // Weak
GOM(sigaction, iFEipp)    // Weak
//GO(__sigaddset, 
//GO(sigaddset, 
//GOW(sigaltstack, 
//GO(sigandset, 
//GOW(sigblock, 
//GO(__sigdelset, 
//GO(sigdelset, 
GO(sigemptyset, iFp)
GO(sigfillset, iFp)
GO(siggetmask, iFv)
//GO(sighold, 
//GO(sigignore, 
//GO(siginterrupt, 
//GO(sigisemptyset, 
//GO(__sigismember, 
GO(sigismember, iFpi)
//GOW(siglongjmp, 
//GOW(signal, 
//GO(signalfd, 
//GO(__signbit, 
//GO(__signbitf, 
//GO(__signbitl, 
//GO(sigorset, 
//GO(__sigpause, 
//GOW(sigpause, 
//GO(sigpending, 
//GOW(sigprocmask, 
//GOW(sigqueue, 
//GO(sigrelse, 
//GOW(sigreturn, 
GOM(sigset, pFEip)
GOM(__sigsetjmp, iFEp)
//GOW(sigsetmask, 
//GO(sigstack, 
//GO(__sigsuspend, 
//GOW(sigsuspend, 
//GO(__sigtimedwait, 
//GOW(sigtimedwait, 
//GO(sigvec, 
//GOW(sigwait, 
//GOW(sigwaitinfo, 
GOW(sleep, uFu)
//GO(__snprintf, 
//GOW(snprintf, 
//GO(__snprintf_chk, 
//GO(sockatmark, 
//GO(__socket, 
//GOW(socket, 
//GOW(socketpair, 
//GO(splice, 
//GO(sprintf, 
//GO(__sprintf_chk, 
//GOW(sprofil, 
GOW(srand, vFu)
//GO(srand48, 
//GOW(srand48_r, 
//GOW(srandom, 
//GOW(srandom_r, 
//GO(sscanf, 
//GOW(ssignal, 
//GO(sstk, 
GOM(__stack_chk_fail, vFE)
//GO(__statfs, 
//GOW(statfs, 
//GOW(statfs64, 
//GOW(statvfs, 
//GOW(statvfs64, 
//GO(statx, 
DATA(stderr, sizeof(void*))
DATA(stdin, sizeof(void*))
DATA(stdout, sizeof(void*))
//GOW(step, 
//GO(stime, 
//GOI(__stpcpy, 
GO(stpcpy, pFpp)
GO(__stpcpy_chk, pFppL)
//GO(__stpcpy_small, 
GO(__stpncpy, pFppL)
GOW(stpncpy, pFppL)
GO(__stpncpy_chk, pFppLL)
GO(__strcasecmp, iFpp)
GO(strcasecmp, iFpp)
//GOI(__strcasecmp_l, 
//GOI(strcasecmp_l, 
GO(__strcasestr, pFpp)
GOW(strcasestr, pFpp)
GO(strcat, pFpp)
GO(__strcat_chk, pFppL)
GO(strchr, pFpi)
GO(strchrnul, pFpi)
GO(strcmp, iFpp)
GO(strcoll, iFpp)
GO(__strcoll_l, iFppp)
GOW(strcoll_l, iFppp)
GO(strcpy, pFpp)
GO(__strcpy_chk, pFppL)
//GO(__strcpy_small, 
GO(strcspn, LFpp)
//GO(__strcspn_c1, 
//GO(__strcspn_c2, 
//GO(__strcspn_c3, 
GO(__strdup, pFp)
GOW(strdup, pFp)
GO(strerror, pFi)
GO(strerror_l, pFip)
//GO(__strerror_r, 
//GOW(strerror_r, 
//GO(strfmon, 
//GO(__strfmon_l, 
//GOW(strfmon_l, 
//GO(strfromd, 
//GO(strfromf, 
//GO(strfromf128, 
//GOW(strfromf32, 
//GOW(strfromf32x, 
//GOW(strfromf64, 
//GOW(strfromf64x, 
//GO(strfroml, 
//GO(strfry, 
//GO(strftime, 
//GO(__strftime_l, 
//GOW(strftime_l, 
GO(strlen, LFp)
GO(strncasecmp, iFppL)
//GOI(__strncasecmp_l, 
//GOI(strncasecmp_l, 
GO(strncat, pFppL)
GO(__strncat_chk, pFppLL)
GO(strncmp, iFppL)
GO(strncpy, pFppL)
GO(__strncpy_chk, pFppLL)
GO(__strndup, pFpL)
GOW(strndup, pFpL)
GO(strnlen, LFpL)
GO(strpbrk, pFpp)
//GO(__strpbrk_c2, 
//GO(__strpbrk_c3, 
//GO(strptime, 
//GOW(strptime_l, 
//GOI(strrchr, 
//GOW(strsep, 
//GO(__strsep_1c, 
//GO(__strsep_2c, 
//GO(__strsep_3c, 
//GO(__strsep_g, 
//GO(strsignal, 
//GOI(strspn, 
//GO(__strspn_c1, 
//GO(__strspn_c2, 
//GO(__strspn_c3, 
GO(strstr, pFpp)
GO(strtod, dFpp)
GO(__strtod_internal, dFppi)
GO(__strtod_l, dFppp)
GOW(strtod_l, dFppp)
//GO(__strtod_nan, 
GO(strtof, fFpp)
//GO(strtof128, 
//GO(__strtof128_internal, 
//GOW(strtof128_l, 
//GO(__strtof128_nan, 
//GOW(strtof32, 
//GOW(strtof32_l, 
//GOW(strtof32x, 
//GOW(strtof32x_l, 
//GOW(strtof64, 
//GOW(strtof64_l, 
//GOW(strtof64x, 
//GOW(strtof64x_l, 
//GO(__strtof_internal, 
//GO(__strtof_l, 
//GOW(strtof_l, 
//GO(__strtof_nan, 
//GO(strtoimax, 
//GO(strtok, 
//GO(__strtok_r, 
//GOW(strtok_r, 
//GO(__strtok_r_1c, 
GOW(strtol, lFppi)
//GO(strtold, 
//GO(__strtold_internal, 
//GO(__strtold_l, 
//GOW(strtold_l, 
//GO(__strtold_nan, 
//GO(__strtol_internal, 
//GO(__strtol_l, 
//GOW(strtol_l, 
//GOW(strtoll, 
//GO(__strtoll_internal, 
//GOW(__strtoll_l, 
//GOW(strtoll_l, 
//GOW(strtoq, 
GOW(strtoul, LFppi)
GO(__strtoul_internal, LFppii)
//GO(__strtoul_l, 
//GOW(strtoul_l, 
//GOW(strtoull, 
//GO(__strtoull_internal, 
//GOW(__strtoull_l, 
//GOW(strtoull_l, 
//GO(strtoumax, 
//GOW(strtouq, 
//GO(__strverscmp, 
GOW(strverscmp, iFpp)
//GO(strxfrm, 
//GO(__strxfrm_l, 
//GOW(strxfrm_l, 
//GO(stty, 
//DATAB(svcauthdes_stats, 
//GO(svcerr_auth, 
//GO(svcerr_decode, 
//GO(svcerr_noproc, 
//GO(svcerr_noprog, 
//GO(svcerr_progvers, 
//GO(svcerr_systemerr, 
//GO(svcerr_weakauth, 
//GO(svc_exit, 
//GO(svcfd_create, 
//DATAB(svc_fdset, 
//GO(svc_getreq, 
//GO(svc_getreq_common, 
//GO(svc_getreq_poll, 
//GO(svc_getreqset, 
//DATAB(svc_max_pollfd, 
//DATAB(svc_pollfd, 
//GO(svcraw_create, 
//GO(svc_register, 
//GO(svc_run, 
//GO(svc_sendreply, 
//GO(svctcp_create, 
//GO(svcudp_bufcreate, 
//GO(svcudp_create, 
//GO(svcudp_enablecache, 
//GO(svcunix_create, 
//GO(svcunixfd_create, 
//GO(svc_unregister, 
//GO(swab, 
GOM(swapcontext, iFEpp) //Weak
//GOW(swapoff, 
//GOW(swapon, 
//GO(swprintf, 
//GO(__swprintf_chk, 
//GO(swscanf, 
//GOW(symlink, 
//GO(symlinkat, 
//GO(sync, 
//GO(sync_file_range, 
//GO(syncfs, 
GOM(syscall, iFEv)
GO(__sysconf, lFi)
GOW(sysconf, lFi)
//GO(__sysctl, 
//GOW(sysctl, 
DATA(_sys_errlist, sizeof(void*))
DATA(sys_errlist, sizeof(void*))
//GOW(sysinfo, 
//GO(syslog, 
//GO(__syslog_chk, 
//DATA(sys_sigabbrev, 
//DATA(sys_sigabbrev, 
//DATA(_sys_siglist, 
//DATA(_sys_siglist, 
//DATA(sys_siglist, 
//DATA(sys_siglist, 
//GOW(system, 
GOM(__sysv_signal, pFip)
//GOW(sysv_signal, 
//GOW(tcdrain, 
//GO(tcflow, 
//GO(tcflush, 
//GOW(tcgetattr, 
//GO(tcgetpgrp, 
//GO(tcgetsid, 
//GO(tcsendbreak, 
//GO(tcsetattr, 
//GO(tcsetpgrp, 
//GO(__tdelete, 
//GOW(tdelete, 
//GOW(tdestroy, 
//GO(tee, 
//GO(telldir, 
//GO(tempnam, 
//GOW(textdomain, 
//GO(__tfind, 
//GOW(tfind, 
//GO(thrd_current, 
//GO(thrd_equal, 
//GO(thrd_sleep, 
//GO(thrd_yield, 
GO(time, LFp)
GO(timegm, LFp)
//GOW(timelocal, 
//GO(timerfd_create, 
//GO(timerfd_gettime, 
//GO(timerfd_settime, 
//GOW(times, 
//GO(timespec_get, 
DATAB(__timezone, sizeof(void*))
GO(tmpfile, pFv)
GOW(tmpfile64, pFv)
GO(tmpnam, pFp)
GO(tmpnam_r, pFp)
GO(toascii, iFi)
//GOW(__toascii_l, 
GO(_tolower, iFi)
GO(tolower, iFi)
//GO(__tolower_l, 
GOW(tolower_l, iFip)
//GO(_toupper, 
GO(toupper, iFi)
//GO(__toupper_l, 
GOW(toupper_l, iFip)
//GO(__towctrans, 
//GOW(towctrans, 
//GO(__towctrans_l, 
//GOW(towctrans_l, 
//GOW(towlower, 
//GO(__towlower_l, 
//GOW(towlower_l, 
//GOW(towupper, 
//GO(__towupper_l, 
//GOW(towupper_l, 
//GO(tr_break, 
//GOW(truncate, 
//GOW(truncate64, 
//GO(__tsearch, 
//GOW(tsearch, 
//GO(ttyname, 
//GOW(ttyname_r, 
//GO(__ttyname_r_chk, 
//GO(ttyslot, 
//GO(__twalk, 
//GOW(twalk, 
DATA(__tzname, 8)
GOW(tzset, vFv)
//GO(ualarm, 
//GO(__uflow, 
//GOW(ulckpwdf, 
//GOW(ulimit, 
//GOW(umask, 
//GOW(umount, 
//GOW(umount2, 
//GOW(uname, 
//GO(__underflow, 
//GOW(ungetc, 
//GO(ungetwc, 
//GOW(unlink, 
//GO(unlinkat, 
//GO(unlockpt, 
GOW(unsetenv, iFp)
//GO(unshare, 
//GOW(updwtmp, 
//GO(updwtmpx, 
//GO(uselib, 
GO(__uselocale, pFp)
GOW(uselocale, pFp)
//GO(user2netname, 
GO(usleep, iFu)
//GO(ustat, 
//GO(utime, 
//GO(utimensat, 
//GOW(utimes, 
//GOW(utmpname, 
//GO(utmpxname, 
//GOW(valloc, 
//GOW(vasprintf, 
//GO(__vasprintf_chk, 
//GOW(vdprintf, 
//GO(__vdprintf_chk, 
//GO(verr, 
//GO(verrx, 
//GOW(versionsort, 
//GOW(versionsort64, 
//GO(__vfork, 
//GOW(vfork, 
GOM(vfprintf, iFEppp)
GOM(__vfprintf_chk, iFEpvpp)
//GO(__vfscanf, 
//GOW(vfscanf, 
//GOW(vfwprintf, 
//GO(__vfwprintf_chk, 
//GOW(vfwscanf, 
//GO(vhangup, 
//GO(vlimit, 
//GO(vmsplice, 
GOM(vprintf, iFEpp)
GOM(__vprintf_chk, iFEvpp)
//GOW(vscanf, 
GOM(__vsnprintf, iFEpLpp)  // Weak
GOM(vsnprintf, iFEpLpp)    // Weak
GOM(__vsnprintf_chk, iFEpLvvpp)
//GOW(vsprintf, 
//GO(__vsprintf_chk, 
//GOW(__vsscanf, 
//GOW(vsscanf, 
GOM(vswprintf, iFEpuppp)    // Weak
GOM(__vswprintf_chk, iFEpuvvppp)    // Weak
//GO(vswscanf, 
//GO(vsyslog, 
//GO(__vsyslog_chk, 
//GO(vtimes, 
//GO(vwarn, 
//GO(vwarnx, 
//GO(vwprintf, 
//GO(__vwprintf_chk, 
//GO(vwscanf, 
//GOW(__wait, 
//GOW(wait, 
//GOW(wait3, 
//GOW(wait4, 
//GOW(waitid, 
GO(__waitpid, lFlpi)
GOW(waitpid, lFlpi)
//GO(warn, 
//GO(warnx, 
//GOW(wcpcpy, 
//GO(__wcpcpy_chk, 
//GOW(wcpncpy, 
//GO(__wcpncpy_chk, 
//GOW(wcrtomb, 
//GO(__wcrtomb_chk, 
//GOW(wcscasecmp, 
//GO(__wcscasecmp_l, 
//GOW(wcscasecmp_l, 
//GOW(wcscat, 
//GO(__wcscat_chk, 
//GOI(wcschr, 
//GOW(wcschrnul, 
//GOI(wcscmp, 
//GOW(wcscoll, 
//GO(__wcscoll_l, 
//GOW(wcscoll_l, 
//GOI(wcscpy, 
//GO(__wcscpy_chk, 
//GO(wcscspn, 
//GO(wcsdup, 
//GO(wcsftime, 
//GO(__wcsftime_l, 
//GOW(wcsftime_l, 
//GOI(wcslen, 
//GOW(wcsncasecmp, 
//GO(__wcsncasecmp_l, 
//GOW(wcsncasecmp_l, 
//GO(wcsncat, 
//GO(__wcsncat_chk, 
//GOI(wcsncmp, 
//GOW(wcsncpy, 
//GO(__wcsncpy_chk, 
//GOW(wcsnrtombs, 
//GO(__wcsnrtombs_chk, 
//GOI(wcsnlen, 
//GO(wcspbrk, 
//GOI(wcsrchr, 
//GOW(wcsrtombs, 
//GO(__wcsrtombs_chk, 
//GO(wcsspn, 
//GO(wcsstr, 
//GO(wcstod, 
//GO(__wcstod_internal, 
//GO(__wcstod_l, 
//GOW(wcstod_l, 
//GO(wcstof, 
//GO(wcstof128, 
//GO(__wcstof128_internal, 
//GOW(wcstof128_l, 
//GOW(wcstof32, 
//GOW(wcstof32_l, 
//GOW(wcstof32x, 
//GOW(wcstof32x_l, 
//GOW(wcstof64, 
//GOW(wcstof64_l, 
//GOW(wcstof64x, 
//GOW(wcstof64x_l, 
//GO(__wcstof_internal, 
//GO(__wcstof_l, 
//GOW(wcstof_l, 
//GO(wcstoimax, 
//GO(wcstok, 
//GOW(wcstol, 
//GO(wcstold, 
//GO(__wcstold_internal, 
//GO(__wcstold_l, 
//GOW(wcstold_l, 
//GO(__wcstol_internal, 
//GO(__wcstol_l, 
//GOW(wcstol_l, 
//GOW(wcstoll, 
//GO(__wcstoll_internal, 
//GOW(__wcstoll_l, 
//GOW(wcstoll_l, 
//GO(wcstombs, 
//GO(__wcstombs_chk, 
//GOW(wcstoq, 
//GOW(wcstoul, 
//GO(__wcstoul_internal, 
//GO(__wcstoul_l, 
//GOW(wcstoul_l, 
//GOW(wcstoull, 
//GO(__wcstoull_internal, 
//GOW(__wcstoull_l, 
//GOW(wcstoull_l, 
//GO(wcstoumax, 
//GOW(wcstouq, 
//GOW(wcswcs, 
//GO(wcswidth, 
//GO(wcsxfrm, 
//GO(__wcsxfrm_l, 
//GOW(wcsxfrm_l, 
GO(wctob, iFi)
GO(wctomb, iFpi)
GO(__wctomb_chk, iFpuL)
//GOW(wctrans, 
//GO(__wctrans_l, 
//GOW(wctrans_l, 
GOW(wctype, LFp)
GOW(wctype_l, LFpp)
GO(__wctype_l, LFpp)
//GO(wcwidth, 
//GOI(wmemchr, 
//GOI(wmemcmp, 
//GOW(wmemcpy, 
//GO(__wmemcpy_chk, 
//GOW(wmemmove, 
//GO(__wmemmove_chk, 
//GOW(wmempcpy, 
//GO(__wmempcpy_chk, 
//GOI(wmemset, 
//GOI(__wmemset_chk, 
//GO(wordexp, 
//GO(wordfree, 
//GO(__woverflow, 
//GO(wprintf, 
//GO(__wprintf_chk, 
GOW(__write, lFipL)
GOW(write, lFipL)
//GO(__write_nocancel, 
GOW(writev, lFipi)
//GO(wscanf, 
//GO(__wuflow, 
//GO(__wunderflow, 
//GO(xdecrypt, 
//GO(xdr_accepted_reply, 
//GO(xdr_array, 
//GO(xdr_authdes_cred, 
//GO(xdr_authdes_verf, 
//GO(xdr_authunix_parms, 
//GO(xdr_bool, 
//GO(xdr_bytes, 
//GO(xdr_callhdr, 
//GO(xdr_callmsg, 
//GO(xdr_char, 
//GO(xdr_cryptkeyarg, 
//GO(xdr_cryptkeyarg2, 
//GO(xdr_cryptkeyres, 
//GO(xdr_des_block, 
//GO(xdr_double, 
//GO(xdr_enum, 
//GO(xdr_float, 
//GO(xdr_free, 
//GO(xdr_getcredres, 
//GO(xdr_hyper, 
//GO(xdr_int, 
//GO(xdr_int16_t, 
//GO(xdr_int32_t, 
//GO(xdr_int64_t, 
//GO(xdr_int8_t, 
//GO(xdr_keybuf, 
//GO(xdr_key_netstarg, 
//GO(xdr_key_netstres, 
//GO(xdr_keystatus, 
//GO(xdr_long, 
//GO(xdr_longlong_t, 
//GO(xdrmem_create, 
//GO(xdr_netnamestr, 
//GO(xdr_netobj, 
//GO(xdr_opaque, 
//GO(xdr_opaque_auth, 
//GO(xdr_pmap, 
//GO(xdr_pmaplist, 
//GO(xdr_pointer, 
//GO(xdr_quad_t, 
//GO(xdrrec_create, 
//GO(xdrrec_endofrecord, 
//GO(xdrrec_eof, 
//GO(xdrrec_skiprecord, 
//GO(xdr_reference, 
//GO(xdr_rejected_reply, 
//GO(xdr_replymsg, 
//GO(xdr_rmtcall_args, 
//GO(xdr_rmtcallres, 
//GO(xdr_short, 
//GO(xdr_sizeof, 
//GO(xdrstdio_create, 
//GO(xdr_string, 
//GO(xdr_u_char, 
//GO(xdr_u_hyper, 
//GO(xdr_u_int, 
//GO(xdr_uint16_t, 
//GO(xdr_uint32_t, 
//GO(xdr_uint64_t, 
//GO(xdr_uint8_t, 
//GO(xdr_u_long, 
//GO(xdr_u_longlong_t, 
//GO(xdr_union, 
//GO(xdr_unixcred, 
//GO(xdr_u_quad_t, 
//GO(xdr_u_short, 
//GO(xdr_vector, 
//GO(xdr_void, 
//GO(xdr_wrapstring, 
//GO(xencrypt, 
//GO(__xmknod, 
//GO(__xmknodat, 
//GO(__xpg_basename, 
//GOW(__xpg_sigpause, 
//GO(__xpg_strerror_r, 
//GO(xprt_register, 
//GO(xprt_unregister, 
GOM(__xstat, iFEipp)
GOM(__xstat64, iFEipp)

GOM(_Jv_RegisterClasses, vFv)   // dummy

GOM(_ITM_addUserCommitAction, vFEpup)
GOM(_ITM_registerTMCloneTable, vFEpu)
GOM(_ITM_deregisterTMCloneTable, vFEp)

GOM(__register_frame_info, vFpp)    // faked function
GOM(__deregister_frame_info, pFp)
