# Requires LLVM-mingw with arm64ec-w64-mingw32-clang on PATH.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64EC)

set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)

set(TRIPLE arm64ec-w64-mingw32)

set(CMAKE_C_COMPILER   ${TRIPLE}-clang)
set(CMAKE_CXX_COMPILER ${TRIPLE}-clang++)
set(CMAKE_ASM_COMPILER ${TRIPLE}-clang)
set(CMAKE_RC_COMPILER  ${TRIPLE}-windres)
set(CMAKE_AR           ${TRIPLE}-ar)
set(CMAKE_RANLIB       ${TRIPLE}-ranlib)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
